// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:crimson_stairs", 716, 15327, 15406, 15338)]
    public class BlockCrimsonStairs : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north" && Half == "top" && Shape == "straight" && Waterlogged == true) {
                    return 15327;
                }

                if(Facing == "north" && Half == "top" && Shape == "straight" && Waterlogged == false) {
                    return 15328;
                }

                if(Facing == "north" && Half == "top" && Shape == "inner_left" && Waterlogged == true) {
                    return 15329;
                }

                if(Facing == "north" && Half == "top" && Shape == "inner_left" && Waterlogged == false) {
                    return 15330;
                }

                if(Facing == "north" && Half == "top" && Shape == "inner_right" && Waterlogged == true) {
                    return 15331;
                }

                if(Facing == "north" && Half == "top" && Shape == "inner_right" && Waterlogged == false) {
                    return 15332;
                }

                if(Facing == "north" && Half == "top" && Shape == "outer_left" && Waterlogged == true) {
                    return 15333;
                }

                if(Facing == "north" && Half == "top" && Shape == "outer_left" && Waterlogged == false) {
                    return 15334;
                }

                if(Facing == "north" && Half == "top" && Shape == "outer_right" && Waterlogged == true) {
                    return 15335;
                }

                if(Facing == "north" && Half == "top" && Shape == "outer_right" && Waterlogged == false) {
                    return 15336;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "straight" && Waterlogged == true) {
                    return 15337;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "straight" && Waterlogged == false) {
                    return 15338;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "inner_left" && Waterlogged == true) {
                    return 15339;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "inner_left" && Waterlogged == false) {
                    return 15340;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "inner_right" && Waterlogged == true) {
                    return 15341;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "inner_right" && Waterlogged == false) {
                    return 15342;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "outer_left" && Waterlogged == true) {
                    return 15343;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "outer_left" && Waterlogged == false) {
                    return 15344;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "outer_right" && Waterlogged == true) {
                    return 15345;
                }

                if(Facing == "north" && Half == "bottom" && Shape == "outer_right" && Waterlogged == false) {
                    return 15346;
                }

                if(Facing == "south" && Half == "top" && Shape == "straight" && Waterlogged == true) {
                    return 15347;
                }

                if(Facing == "south" && Half == "top" && Shape == "straight" && Waterlogged == false) {
                    return 15348;
                }

                if(Facing == "south" && Half == "top" && Shape == "inner_left" && Waterlogged == true) {
                    return 15349;
                }

                if(Facing == "south" && Half == "top" && Shape == "inner_left" && Waterlogged == false) {
                    return 15350;
                }

                if(Facing == "south" && Half == "top" && Shape == "inner_right" && Waterlogged == true) {
                    return 15351;
                }

                if(Facing == "south" && Half == "top" && Shape == "inner_right" && Waterlogged == false) {
                    return 15352;
                }

                if(Facing == "south" && Half == "top" && Shape == "outer_left" && Waterlogged == true) {
                    return 15353;
                }

                if(Facing == "south" && Half == "top" && Shape == "outer_left" && Waterlogged == false) {
                    return 15354;
                }

                if(Facing == "south" && Half == "top" && Shape == "outer_right" && Waterlogged == true) {
                    return 15355;
                }

                if(Facing == "south" && Half == "top" && Shape == "outer_right" && Waterlogged == false) {
                    return 15356;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "straight" && Waterlogged == true) {
                    return 15357;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "straight" && Waterlogged == false) {
                    return 15358;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "inner_left" && Waterlogged == true) {
                    return 15359;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "inner_left" && Waterlogged == false) {
                    return 15360;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "inner_right" && Waterlogged == true) {
                    return 15361;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "inner_right" && Waterlogged == false) {
                    return 15362;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "outer_left" && Waterlogged == true) {
                    return 15363;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "outer_left" && Waterlogged == false) {
                    return 15364;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "outer_right" && Waterlogged == true) {
                    return 15365;
                }

                if(Facing == "south" && Half == "bottom" && Shape == "outer_right" && Waterlogged == false) {
                    return 15366;
                }

                if(Facing == "west" && Half == "top" && Shape == "straight" && Waterlogged == true) {
                    return 15367;
                }

                if(Facing == "west" && Half == "top" && Shape == "straight" && Waterlogged == false) {
                    return 15368;
                }

                if(Facing == "west" && Half == "top" && Shape == "inner_left" && Waterlogged == true) {
                    return 15369;
                }

                if(Facing == "west" && Half == "top" && Shape == "inner_left" && Waterlogged == false) {
                    return 15370;
                }

                if(Facing == "west" && Half == "top" && Shape == "inner_right" && Waterlogged == true) {
                    return 15371;
                }

                if(Facing == "west" && Half == "top" && Shape == "inner_right" && Waterlogged == false) {
                    return 15372;
                }

                if(Facing == "west" && Half == "top" && Shape == "outer_left" && Waterlogged == true) {
                    return 15373;
                }

                if(Facing == "west" && Half == "top" && Shape == "outer_left" && Waterlogged == false) {
                    return 15374;
                }

                if(Facing == "west" && Half == "top" && Shape == "outer_right" && Waterlogged == true) {
                    return 15375;
                }

                if(Facing == "west" && Half == "top" && Shape == "outer_right" && Waterlogged == false) {
                    return 15376;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "straight" && Waterlogged == true) {
                    return 15377;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "straight" && Waterlogged == false) {
                    return 15378;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "inner_left" && Waterlogged == true) {
                    return 15379;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "inner_left" && Waterlogged == false) {
                    return 15380;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "inner_right" && Waterlogged == true) {
                    return 15381;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "inner_right" && Waterlogged == false) {
                    return 15382;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "outer_left" && Waterlogged == true) {
                    return 15383;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "outer_left" && Waterlogged == false) {
                    return 15384;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "outer_right" && Waterlogged == true) {
                    return 15385;
                }

                if(Facing == "west" && Half == "bottom" && Shape == "outer_right" && Waterlogged == false) {
                    return 15386;
                }

                if(Facing == "east" && Half == "top" && Shape == "straight" && Waterlogged == true) {
                    return 15387;
                }

                if(Facing == "east" && Half == "top" && Shape == "straight" && Waterlogged == false) {
                    return 15388;
                }

                if(Facing == "east" && Half == "top" && Shape == "inner_left" && Waterlogged == true) {
                    return 15389;
                }

                if(Facing == "east" && Half == "top" && Shape == "inner_left" && Waterlogged == false) {
                    return 15390;
                }

                if(Facing == "east" && Half == "top" && Shape == "inner_right" && Waterlogged == true) {
                    return 15391;
                }

                if(Facing == "east" && Half == "top" && Shape == "inner_right" && Waterlogged == false) {
                    return 15392;
                }

                if(Facing == "east" && Half == "top" && Shape == "outer_left" && Waterlogged == true) {
                    return 15393;
                }

                if(Facing == "east" && Half == "top" && Shape == "outer_left" && Waterlogged == false) {
                    return 15394;
                }

                if(Facing == "east" && Half == "top" && Shape == "outer_right" && Waterlogged == true) {
                    return 15395;
                }

                if(Facing == "east" && Half == "top" && Shape == "outer_right" && Waterlogged == false) {
                    return 15396;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "straight" && Waterlogged == true) {
                    return 15397;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "straight" && Waterlogged == false) {
                    return 15398;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "inner_left" && Waterlogged == true) {
                    return 15399;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "inner_left" && Waterlogged == false) {
                    return 15400;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "inner_right" && Waterlogged == true) {
                    return 15401;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "inner_right" && Waterlogged == false) {
                    return 15402;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "outer_left" && Waterlogged == true) {
                    return 15403;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "outer_left" && Waterlogged == false) {
                    return 15404;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "outer_right" && Waterlogged == true) {
                    return 15405;
                }

                if(Facing == "east" && Half == "bottom" && Shape == "outer_right" && Waterlogged == false) {
                    return 15406;
                }

                return DefaultState;
            }

            set {
                if(value == 15327) {
                    Facing = "north";
Half = "top";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15328) {
                    Facing = "north";
Half = "top";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15329) {
                    Facing = "north";
Half = "top";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15330) {
                    Facing = "north";
Half = "top";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15331) {
                    Facing = "north";
Half = "top";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15332) {
                    Facing = "north";
Half = "top";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15333) {
                    Facing = "north";
Half = "top";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15334) {
                    Facing = "north";
Half = "top";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15335) {
                    Facing = "north";
Half = "top";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15336) {
                    Facing = "north";
Half = "top";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15337) {
                    Facing = "north";
Half = "bottom";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15338) {
                    Facing = "north";
Half = "bottom";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15339) {
                    Facing = "north";
Half = "bottom";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15340) {
                    Facing = "north";
Half = "bottom";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15341) {
                    Facing = "north";
Half = "bottom";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15342) {
                    Facing = "north";
Half = "bottom";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15343) {
                    Facing = "north";
Half = "bottom";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15344) {
                    Facing = "north";
Half = "bottom";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15345) {
                    Facing = "north";
Half = "bottom";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15346) {
                    Facing = "north";
Half = "bottom";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15347) {
                    Facing = "south";
Half = "top";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15348) {
                    Facing = "south";
Half = "top";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15349) {
                    Facing = "south";
Half = "top";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15350) {
                    Facing = "south";
Half = "top";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15351) {
                    Facing = "south";
Half = "top";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15352) {
                    Facing = "south";
Half = "top";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15353) {
                    Facing = "south";
Half = "top";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15354) {
                    Facing = "south";
Half = "top";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15355) {
                    Facing = "south";
Half = "top";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15356) {
                    Facing = "south";
Half = "top";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15357) {
                    Facing = "south";
Half = "bottom";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15358) {
                    Facing = "south";
Half = "bottom";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15359) {
                    Facing = "south";
Half = "bottom";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15360) {
                    Facing = "south";
Half = "bottom";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15361) {
                    Facing = "south";
Half = "bottom";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15362) {
                    Facing = "south";
Half = "bottom";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15363) {
                    Facing = "south";
Half = "bottom";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15364) {
                    Facing = "south";
Half = "bottom";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15365) {
                    Facing = "south";
Half = "bottom";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15366) {
                    Facing = "south";
Half = "bottom";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15367) {
                    Facing = "west";
Half = "top";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15368) {
                    Facing = "west";
Half = "top";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15369) {
                    Facing = "west";
Half = "top";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15370) {
                    Facing = "west";
Half = "top";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15371) {
                    Facing = "west";
Half = "top";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15372) {
                    Facing = "west";
Half = "top";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15373) {
                    Facing = "west";
Half = "top";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15374) {
                    Facing = "west";
Half = "top";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15375) {
                    Facing = "west";
Half = "top";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15376) {
                    Facing = "west";
Half = "top";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15377) {
                    Facing = "west";
Half = "bottom";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15378) {
                    Facing = "west";
Half = "bottom";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15379) {
                    Facing = "west";
Half = "bottom";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15380) {
                    Facing = "west";
Half = "bottom";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15381) {
                    Facing = "west";
Half = "bottom";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15382) {
                    Facing = "west";
Half = "bottom";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15383) {
                    Facing = "west";
Half = "bottom";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15384) {
                    Facing = "west";
Half = "bottom";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15385) {
                    Facing = "west";
Half = "bottom";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15386) {
                    Facing = "west";
Half = "bottom";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15387) {
                    Facing = "east";
Half = "top";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15388) {
                    Facing = "east";
Half = "top";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15389) {
                    Facing = "east";
Half = "top";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15390) {
                    Facing = "east";
Half = "top";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15391) {
                    Facing = "east";
Half = "top";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15392) {
                    Facing = "east";
Half = "top";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15393) {
                    Facing = "east";
Half = "top";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15394) {
                    Facing = "east";
Half = "top";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15395) {
                    Facing = "east";
Half = "top";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15396) {
                    Facing = "east";
Half = "top";
Shape = "outer_right";
Waterlogged = false;
                }

                if(value == 15397) {
                    Facing = "east";
Half = "bottom";
Shape = "straight";
Waterlogged = true;
                }

                if(value == 15398) {
                    Facing = "east";
Half = "bottom";
Shape = "straight";
Waterlogged = false;
                }

                if(value == 15399) {
                    Facing = "east";
Half = "bottom";
Shape = "inner_left";
Waterlogged = true;
                }

                if(value == 15400) {
                    Facing = "east";
Half = "bottom";
Shape = "inner_left";
Waterlogged = false;
                }

                if(value == 15401) {
                    Facing = "east";
Half = "bottom";
Shape = "inner_right";
Waterlogged = true;
                }

                if(value == 15402) {
                    Facing = "east";
Half = "bottom";
Shape = "inner_right";
Waterlogged = false;
                }

                if(value == 15403) {
                    Facing = "east";
Half = "bottom";
Shape = "outer_left";
Waterlogged = true;
                }

                if(value == 15404) {
                    Facing = "east";
Half = "bottom";
Shape = "outer_left";
Waterlogged = false;
                }

                if(value == 15405) {
                    Facing = "east";
Half = "bottom";
Shape = "outer_right";
Waterlogged = true;
                }

                if(value == 15406) {
                    Facing = "east";
Half = "bottom";
Shape = "outer_right";
Waterlogged = false;
                }

            }
        }

        public string Facing { get; set; } = "north";
        public string Half { get; set; } = "bottom";
        public string Shape { get; set; } = "straight";
        public bool Waterlogged { get; set; } = false;

        public BlockCrimsonStairs() {
            State = DefaultState;
        }

        public BlockCrimsonStairs(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockCrimsonStairs(string facing, string half, string shape, bool waterlogged) {
            Facing = facing;
            Half = half;
            Shape = shape;
            Waterlogged = waterlogged;
        }
    }
}