// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:tripwire_hook", 271, 5263, 5278, 5272)]
    public class BlockTripwireHook : BlockBase {

        public override ushort State {
            get {
                if(Attached == true && Facing == "north" && Powered == true) {
                    return 5263;
                }

                if(Attached == true && Facing == "north" && Powered == false) {
                    return 5264;
                }

                if(Attached == true && Facing == "south" && Powered == true) {
                    return 5265;
                }

                if(Attached == true && Facing == "south" && Powered == false) {
                    return 5266;
                }

                if(Attached == true && Facing == "west" && Powered == true) {
                    return 5267;
                }

                if(Attached == true && Facing == "west" && Powered == false) {
                    return 5268;
                }

                if(Attached == true && Facing == "east" && Powered == true) {
                    return 5269;
                }

                if(Attached == true && Facing == "east" && Powered == false) {
                    return 5270;
                }

                if(Attached == false && Facing == "north" && Powered == true) {
                    return 5271;
                }

                if(Attached == false && Facing == "north" && Powered == false) {
                    return 5272;
                }

                if(Attached == false && Facing == "south" && Powered == true) {
                    return 5273;
                }

                if(Attached == false && Facing == "south" && Powered == false) {
                    return 5274;
                }

                if(Attached == false && Facing == "west" && Powered == true) {
                    return 5275;
                }

                if(Attached == false && Facing == "west" && Powered == false) {
                    return 5276;
                }

                if(Attached == false && Facing == "east" && Powered == true) {
                    return 5277;
                }

                if(Attached == false && Facing == "east" && Powered == false) {
                    return 5278;
                }

                return DefaultState;
            }

            set {
                if(value == 5263) {
                    Attached = true;
Facing = "north";
Powered = true;
                }

                if(value == 5264) {
                    Attached = true;
Facing = "north";
Powered = false;
                }

                if(value == 5265) {
                    Attached = true;
Facing = "south";
Powered = true;
                }

                if(value == 5266) {
                    Attached = true;
Facing = "south";
Powered = false;
                }

                if(value == 5267) {
                    Attached = true;
Facing = "west";
Powered = true;
                }

                if(value == 5268) {
                    Attached = true;
Facing = "west";
Powered = false;
                }

                if(value == 5269) {
                    Attached = true;
Facing = "east";
Powered = true;
                }

                if(value == 5270) {
                    Attached = true;
Facing = "east";
Powered = false;
                }

                if(value == 5271) {
                    Attached = false;
Facing = "north";
Powered = true;
                }

                if(value == 5272) {
                    Attached = false;
Facing = "north";
Powered = false;
                }

                if(value == 5273) {
                    Attached = false;
Facing = "south";
Powered = true;
                }

                if(value == 5274) {
                    Attached = false;
Facing = "south";
Powered = false;
                }

                if(value == 5275) {
                    Attached = false;
Facing = "west";
Powered = true;
                }

                if(value == 5276) {
                    Attached = false;
Facing = "west";
Powered = false;
                }

                if(value == 5277) {
                    Attached = false;
Facing = "east";
Powered = true;
                }

                if(value == 5278) {
                    Attached = false;
Facing = "east";
Powered = false;
                }

            }
        }

        public bool Attached { get; set; } = false;
        public string Facing { get; set; } = "north";
        public bool Powered { get; set; } = false;

        public BlockTripwireHook() {
            State = DefaultState;
        }

        public BlockTripwireHook(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockTripwireHook(bool attached, string facing, bool powered) {
            Attached = attached;
            Facing = facing;
            Powered = powered;
        }
    }
}