// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:activator_rail", 341, 6827, 6838, 6833)]
    public class BlockActivatorRail : BlockBase {

        public override ushort State {
            get {
                if(Powered == true && Shape == "north_south") {
                    return 6827;
                }

                if(Powered == true && Shape == "east_west") {
                    return 6828;
                }

                if(Powered == true && Shape == "ascending_east") {
                    return 6829;
                }

                if(Powered == true && Shape == "ascending_west") {
                    return 6830;
                }

                if(Powered == true && Shape == "ascending_north") {
                    return 6831;
                }

                if(Powered == true && Shape == "ascending_south") {
                    return 6832;
                }

                if(Powered == false && Shape == "north_south") {
                    return 6833;
                }

                if(Powered == false && Shape == "east_west") {
                    return 6834;
                }

                if(Powered == false && Shape == "ascending_east") {
                    return 6835;
                }

                if(Powered == false && Shape == "ascending_west") {
                    return 6836;
                }

                if(Powered == false && Shape == "ascending_north") {
                    return 6837;
                }

                if(Powered == false && Shape == "ascending_south") {
                    return 6838;
                }

                return DefaultState;
            }

            set {
                if(value == 6827) {
                    Powered = true;
Shape = "north_south";
                }

                if(value == 6828) {
                    Powered = true;
Shape = "east_west";
                }

                if(value == 6829) {
                    Powered = true;
Shape = "ascending_east";
                }

                if(value == 6830) {
                    Powered = true;
Shape = "ascending_west";
                }

                if(value == 6831) {
                    Powered = true;
Shape = "ascending_north";
                }

                if(value == 6832) {
                    Powered = true;
Shape = "ascending_south";
                }

                if(value == 6833) {
                    Powered = false;
Shape = "north_south";
                }

                if(value == 6834) {
                    Powered = false;
Shape = "east_west";
                }

                if(value == 6835) {
                    Powered = false;
Shape = "ascending_east";
                }

                if(value == 6836) {
                    Powered = false;
Shape = "ascending_west";
                }

                if(value == 6837) {
                    Powered = false;
Shape = "ascending_north";
                }

                if(value == 6838) {
                    Powered = false;
Shape = "ascending_south";
                }

            }
        }

        public bool Powered { get; set; } = false;
        public string Shape { get; set; } = "north_south";

        public BlockActivatorRail() {
            State = DefaultState;
        }

        public BlockActivatorRail(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockActivatorRail(bool powered, string shape) {
            Powered = powered;
            Shape = shape;
        }
    }
}