// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:cut_sandstone_slab", 461, 8358, 8363, 8361)]
    public class BlockCutSandstoneSlab : BlockBase {

        public override ushort State {
            get {
                if(Type == "top" && Waterlogged == true) {
                    return 8358;
                }

                if(Type == "top" && Waterlogged == false) {
                    return 8359;
                }

                if(Type == "bottom" && Waterlogged == true) {
                    return 8360;
                }

                if(Type == "bottom" && Waterlogged == false) {
                    return 8361;
                }

                if(Type == "double" && Waterlogged == true) {
                    return 8362;
                }

                if(Type == "double" && Waterlogged == false) {
                    return 8363;
                }

                return DefaultState;
            }

            set {
                if(value == 8358) {
                    Type = "top";
Waterlogged = true;
                }

                if(value == 8359) {
                    Type = "top";
Waterlogged = false;
                }

                if(value == 8360) {
                    Type = "bottom";
Waterlogged = true;
                }

                if(value == 8361) {
                    Type = "bottom";
Waterlogged = false;
                }

                if(value == 8362) {
                    Type = "double";
Waterlogged = true;
                }

                if(value == 8363) {
                    Type = "double";
Waterlogged = false;
                }

            }
        }

        public string Type { get; set; } = "bottom";
        public bool Waterlogged { get; set; } = false;

        public BlockCutSandstoneSlab() {
            State = DefaultState;
        }

        public BlockCutSandstoneSlab(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockCutSandstoneSlab(string type, bool waterlogged) {
            Type = type;
            Waterlogged = waterlogged;
        }
    }
}