// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:infested_chiseled_stone_bricks", 237, 4504, 4504, 4504)]
    public class BlockInfestedChiseledStoneBricks : BlockBase {

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockInfestedChiseledStoneBricks() {
            State = DefaultState;
        }

        public BlockInfestedChiseledStoneBricks(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}