// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:brown_shulker_box", 522, 9354, 9359, 9358)]
    public class BlockBrownShulkerBox : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9354;
                }

                if(Facing == "east") {
                    return 9355;
                }

                if(Facing == "south") {
                    return 9356;
                }

                if(Facing == "west") {
                    return 9357;
                }

                if(Facing == "up") {
                    return 9358;
                }

                if(Facing == "down") {
                    return 9359;
                }

                return DefaultState;
            }

            set {
                if(value == 9354) {
                    Facing = "north";
                }

                if(value == 9355) {
                    Facing = "east";
                }

                if(value == 9356) {
                    Facing = "south";
                }

                if(value == 9357) {
                    Facing = "west";
                }

                if(value == 9358) {
                    Facing = "up";
                }

                if(value == 9359) {
                    Facing = "down";
                }

            }
        }

        public string Facing { get; set; } = "up";

        public BlockBrownShulkerBox() {
            State = DefaultState;
        }

        public BlockBrownShulkerBox(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockBrownShulkerBox(string facing) {
            Facing = facing;
        }
    }
}