// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:oak_door", 161, 3573, 3636, 3584)]
    public class BlockOakDoor : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north" && Half == "upper" && Hinge == "left" && Open == true && Powered == true) {
                    return 3573;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "left" && Open == true && Powered == false) {
                    return 3574;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "left" && Open == false && Powered == true) {
                    return 3575;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "left" && Open == false && Powered == false) {
                    return 3576;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "right" && Open == true && Powered == true) {
                    return 3577;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "right" && Open == true && Powered == false) {
                    return 3578;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "right" && Open == false && Powered == true) {
                    return 3579;
                }

                if(Facing == "north" && Half == "upper" && Hinge == "right" && Open == false && Powered == false) {
                    return 3580;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "left" && Open == true && Powered == true) {
                    return 3581;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "left" && Open == true && Powered == false) {
                    return 3582;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "left" && Open == false && Powered == true) {
                    return 3583;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "left" && Open == false && Powered == false) {
                    return 3584;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "right" && Open == true && Powered == true) {
                    return 3585;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "right" && Open == true && Powered == false) {
                    return 3586;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "right" && Open == false && Powered == true) {
                    return 3587;
                }

                if(Facing == "north" && Half == "lower" && Hinge == "right" && Open == false && Powered == false) {
                    return 3588;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "left" && Open == true && Powered == true) {
                    return 3589;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "left" && Open == true && Powered == false) {
                    return 3590;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "left" && Open == false && Powered == true) {
                    return 3591;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "left" && Open == false && Powered == false) {
                    return 3592;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "right" && Open == true && Powered == true) {
                    return 3593;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "right" && Open == true && Powered == false) {
                    return 3594;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "right" && Open == false && Powered == true) {
                    return 3595;
                }

                if(Facing == "south" && Half == "upper" && Hinge == "right" && Open == false && Powered == false) {
                    return 3596;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "left" && Open == true && Powered == true) {
                    return 3597;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "left" && Open == true && Powered == false) {
                    return 3598;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "left" && Open == false && Powered == true) {
                    return 3599;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "left" && Open == false && Powered == false) {
                    return 3600;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "right" && Open == true && Powered == true) {
                    return 3601;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "right" && Open == true && Powered == false) {
                    return 3602;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "right" && Open == false && Powered == true) {
                    return 3603;
                }

                if(Facing == "south" && Half == "lower" && Hinge == "right" && Open == false && Powered == false) {
                    return 3604;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "left" && Open == true && Powered == true) {
                    return 3605;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "left" && Open == true && Powered == false) {
                    return 3606;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "left" && Open == false && Powered == true) {
                    return 3607;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "left" && Open == false && Powered == false) {
                    return 3608;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "right" && Open == true && Powered == true) {
                    return 3609;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "right" && Open == true && Powered == false) {
                    return 3610;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "right" && Open == false && Powered == true) {
                    return 3611;
                }

                if(Facing == "west" && Half == "upper" && Hinge == "right" && Open == false && Powered == false) {
                    return 3612;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "left" && Open == true && Powered == true) {
                    return 3613;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "left" && Open == true && Powered == false) {
                    return 3614;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "left" && Open == false && Powered == true) {
                    return 3615;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "left" && Open == false && Powered == false) {
                    return 3616;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "right" && Open == true && Powered == true) {
                    return 3617;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "right" && Open == true && Powered == false) {
                    return 3618;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "right" && Open == false && Powered == true) {
                    return 3619;
                }

                if(Facing == "west" && Half == "lower" && Hinge == "right" && Open == false && Powered == false) {
                    return 3620;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "left" && Open == true && Powered == true) {
                    return 3621;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "left" && Open == true && Powered == false) {
                    return 3622;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "left" && Open == false && Powered == true) {
                    return 3623;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "left" && Open == false && Powered == false) {
                    return 3624;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "right" && Open == true && Powered == true) {
                    return 3625;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "right" && Open == true && Powered == false) {
                    return 3626;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "right" && Open == false && Powered == true) {
                    return 3627;
                }

                if(Facing == "east" && Half == "upper" && Hinge == "right" && Open == false && Powered == false) {
                    return 3628;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "left" && Open == true && Powered == true) {
                    return 3629;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "left" && Open == true && Powered == false) {
                    return 3630;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "left" && Open == false && Powered == true) {
                    return 3631;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "left" && Open == false && Powered == false) {
                    return 3632;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "right" && Open == true && Powered == true) {
                    return 3633;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "right" && Open == true && Powered == false) {
                    return 3634;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "right" && Open == false && Powered == true) {
                    return 3635;
                }

                if(Facing == "east" && Half == "lower" && Hinge == "right" && Open == false && Powered == false) {
                    return 3636;
                }

                return DefaultState;
            }

            set {
                if(value == 3573) {
                    Facing = "north";
Half = "upper";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3574) {
                    Facing = "north";
Half = "upper";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3575) {
                    Facing = "north";
Half = "upper";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3576) {
                    Facing = "north";
Half = "upper";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3577) {
                    Facing = "north";
Half = "upper";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3578) {
                    Facing = "north";
Half = "upper";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3579) {
                    Facing = "north";
Half = "upper";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3580) {
                    Facing = "north";
Half = "upper";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3581) {
                    Facing = "north";
Half = "lower";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3582) {
                    Facing = "north";
Half = "lower";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3583) {
                    Facing = "north";
Half = "lower";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3584) {
                    Facing = "north";
Half = "lower";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3585) {
                    Facing = "north";
Half = "lower";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3586) {
                    Facing = "north";
Half = "lower";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3587) {
                    Facing = "north";
Half = "lower";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3588) {
                    Facing = "north";
Half = "lower";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3589) {
                    Facing = "south";
Half = "upper";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3590) {
                    Facing = "south";
Half = "upper";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3591) {
                    Facing = "south";
Half = "upper";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3592) {
                    Facing = "south";
Half = "upper";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3593) {
                    Facing = "south";
Half = "upper";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3594) {
                    Facing = "south";
Half = "upper";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3595) {
                    Facing = "south";
Half = "upper";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3596) {
                    Facing = "south";
Half = "upper";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3597) {
                    Facing = "south";
Half = "lower";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3598) {
                    Facing = "south";
Half = "lower";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3599) {
                    Facing = "south";
Half = "lower";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3600) {
                    Facing = "south";
Half = "lower";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3601) {
                    Facing = "south";
Half = "lower";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3602) {
                    Facing = "south";
Half = "lower";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3603) {
                    Facing = "south";
Half = "lower";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3604) {
                    Facing = "south";
Half = "lower";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3605) {
                    Facing = "west";
Half = "upper";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3606) {
                    Facing = "west";
Half = "upper";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3607) {
                    Facing = "west";
Half = "upper";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3608) {
                    Facing = "west";
Half = "upper";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3609) {
                    Facing = "west";
Half = "upper";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3610) {
                    Facing = "west";
Half = "upper";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3611) {
                    Facing = "west";
Half = "upper";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3612) {
                    Facing = "west";
Half = "upper";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3613) {
                    Facing = "west";
Half = "lower";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3614) {
                    Facing = "west";
Half = "lower";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3615) {
                    Facing = "west";
Half = "lower";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3616) {
                    Facing = "west";
Half = "lower";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3617) {
                    Facing = "west";
Half = "lower";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3618) {
                    Facing = "west";
Half = "lower";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3619) {
                    Facing = "west";
Half = "lower";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3620) {
                    Facing = "west";
Half = "lower";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3621) {
                    Facing = "east";
Half = "upper";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3622) {
                    Facing = "east";
Half = "upper";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3623) {
                    Facing = "east";
Half = "upper";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3624) {
                    Facing = "east";
Half = "upper";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3625) {
                    Facing = "east";
Half = "upper";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3626) {
                    Facing = "east";
Half = "upper";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3627) {
                    Facing = "east";
Half = "upper";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3628) {
                    Facing = "east";
Half = "upper";
Hinge = "right";
Open = false;
Powered = false;
                }

                if(value == 3629) {
                    Facing = "east";
Half = "lower";
Hinge = "left";
Open = true;
Powered = true;
                }

                if(value == 3630) {
                    Facing = "east";
Half = "lower";
Hinge = "left";
Open = true;
Powered = false;
                }

                if(value == 3631) {
                    Facing = "east";
Half = "lower";
Hinge = "left";
Open = false;
Powered = true;
                }

                if(value == 3632) {
                    Facing = "east";
Half = "lower";
Hinge = "left";
Open = false;
Powered = false;
                }

                if(value == 3633) {
                    Facing = "east";
Half = "lower";
Hinge = "right";
Open = true;
Powered = true;
                }

                if(value == 3634) {
                    Facing = "east";
Half = "lower";
Hinge = "right";
Open = true;
Powered = false;
                }

                if(value == 3635) {
                    Facing = "east";
Half = "lower";
Hinge = "right";
Open = false;
Powered = true;
                }

                if(value == 3636) {
                    Facing = "east";
Half = "lower";
Hinge = "right";
Open = false;
Powered = false;
                }

            }
        }

        public string Facing { get; set; } = "north";
        public string Half { get; set; } = "lower";
        public string Hinge { get; set; } = "left";
        public bool Open { get; set; } = false;
        public bool Powered { get; set; } = false;

        public BlockOakDoor() {
            State = DefaultState;
        }

        public BlockOakDoor(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockOakDoor(string facing, string half, string hinge, bool open, bool powered) {
            Facing = facing;
            Half = half;
            Hinge = hinge;
            Open = open;
            Powered = powered;
        }
    }
}