// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:dead_tube_coral_block", 578, 9514, 9514, 9514)]
    public class BlockDeadTubeCoralBlock : BlockBase {

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockDeadTubeCoralBlock() {
            State = DefaultState;
        }

        public BlockDeadTubeCoralBlock(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}