// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:frosted_ice", 502, 9253, 9256, 9253)]
    public class BlockFrostedIce : BlockBase {

        public override ushort State {
            get {
                if(Age == 0) {
                    return 9253;
                }

                if(Age == 1) {
                    return 9254;
                }

                if(Age == 2) {
                    return 9255;
                }

                if(Age == 3) {
                    return 9256;
                }

                return DefaultState;
            }

            set {
                if(value == 9253) {
                    Age = 0;
                }

                if(value == 9254) {
                    Age = 1;
                }

                if(value == 9255) {
                    Age = 2;
                }

                if(value == 9256) {
                    Age = 3;
                }

            }
        }

        public int Age { get; set; } = 0;

        public BlockFrostedIce() {
            State = DefaultState;
        }

        public BlockFrostedIce(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockFrostedIce(int age) {
            Age = age;
        }
    }
}