// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:polished_basalt", 197, 4005, 4007, 4006)]
    public class BlockPolishedBasalt : BlockBase {

        public override ushort State {
            get {
                if(Axis == "x") {
                    return 4005;
                }

                if(Axis == "y") {
                    return 4006;
                }

                if(Axis == "z") {
                    return 4007;
                }

                return DefaultState;
            }

            set {
                if(value == 4005) {
                    Axis = "x";
                }

                if(value == 4006) {
                    Axis = "y";
                }

                if(value == 4007) {
                    Axis = "z";
                }

            }
        }

        public string Axis { get; set; } = "y";

        public BlockPolishedBasalt() {
            State = DefaultState;
        }

        public BlockPolishedBasalt(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockPolishedBasalt(string axis) {
            Axis = axis;
        }
    }
}