// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:cracked_polished_blackstone_bricks", 749, 16260, 16260, 16260)]
    public class BlockCrackedPolishedBlackstoneBricks : BlockBase {

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockCrackedPolishedBlackstoneBricks() {
            State = DefaultState;
        }

        public BlockCrackedPolishedBlackstoneBricks(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}