// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:birch_pressure_plate", 176, 3877, 3878, 3878)]
    public class BlockBirchPressurePlate : BlockBase {

        public override ushort State {
            get {
                if(Powered == true) {
                    return 3877;
                }

                if(Powered == false) {
                    return 3878;
                }

                return DefaultState;
            }

            set {
                if(value == 3877) {
                    Powered = true;
                }

                if(value == 3878) {
                    Powered = false;
                }

            }
        }

        public bool Powered { get; set; } = false;

        public BlockBirchPressurePlate() {
            State = DefaultState;
        }

        public BlockBirchPressurePlate(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockBirchPressurePlate(bool powered) {
            Powered = powered;
        }
    }
}