// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace Starfield.Core.Block.Blocks {

    [Block("minecraft:lime_stained_glass_pane", 364, 7027, 7058, 7058)]
    public class BlockLimeStainedGlassPane : BlockBase {

        public override ushort State {
            get {
                if(East == true && North == true && South == true && Waterlogged == true && West == true) {
                    return 7027;
                }

                if(East == true && North == true && South == true && Waterlogged == true && West == false) {
                    return 7028;
                }

                if(East == true && North == true && South == true && Waterlogged == false && West == true) {
                    return 7029;
                }

                if(East == true && North == true && South == true && Waterlogged == false && West == false) {
                    return 7030;
                }

                if(East == true && North == true && South == false && Waterlogged == true && West == true) {
                    return 7031;
                }

                if(East == true && North == true && South == false && Waterlogged == true && West == false) {
                    return 7032;
                }

                if(East == true && North == true && South == false && Waterlogged == false && West == true) {
                    return 7033;
                }

                if(East == true && North == true && South == false && Waterlogged == false && West == false) {
                    return 7034;
                }

                if(East == true && North == false && South == true && Waterlogged == true && West == true) {
                    return 7035;
                }

                if(East == true && North == false && South == true && Waterlogged == true && West == false) {
                    return 7036;
                }

                if(East == true && North == false && South == true && Waterlogged == false && West == true) {
                    return 7037;
                }

                if(East == true && North == false && South == true && Waterlogged == false && West == false) {
                    return 7038;
                }

                if(East == true && North == false && South == false && Waterlogged == true && West == true) {
                    return 7039;
                }

                if(East == true && North == false && South == false && Waterlogged == true && West == false) {
                    return 7040;
                }

                if(East == true && North == false && South == false && Waterlogged == false && West == true) {
                    return 7041;
                }

                if(East == true && North == false && South == false && Waterlogged == false && West == false) {
                    return 7042;
                }

                if(East == false && North == true && South == true && Waterlogged == true && West == true) {
                    return 7043;
                }

                if(East == false && North == true && South == true && Waterlogged == true && West == false) {
                    return 7044;
                }

                if(East == false && North == true && South == true && Waterlogged == false && West == true) {
                    return 7045;
                }

                if(East == false && North == true && South == true && Waterlogged == false && West == false) {
                    return 7046;
                }

                if(East == false && North == true && South == false && Waterlogged == true && West == true) {
                    return 7047;
                }

                if(East == false && North == true && South == false && Waterlogged == true && West == false) {
                    return 7048;
                }

                if(East == false && North == true && South == false && Waterlogged == false && West == true) {
                    return 7049;
                }

                if(East == false && North == true && South == false && Waterlogged == false && West == false) {
                    return 7050;
                }

                if(East == false && North == false && South == true && Waterlogged == true && West == true) {
                    return 7051;
                }

                if(East == false && North == false && South == true && Waterlogged == true && West == false) {
                    return 7052;
                }

                if(East == false && North == false && South == true && Waterlogged == false && West == true) {
                    return 7053;
                }

                if(East == false && North == false && South == true && Waterlogged == false && West == false) {
                    return 7054;
                }

                if(East == false && North == false && South == false && Waterlogged == true && West == true) {
                    return 7055;
                }

                if(East == false && North == false && South == false && Waterlogged == true && West == false) {
                    return 7056;
                }

                if(East == false && North == false && South == false && Waterlogged == false && West == true) {
                    return 7057;
                }

                if(East == false && North == false && South == false && Waterlogged == false && West == false) {
                    return 7058;
                }

                return DefaultState;
            }

            set {
                if(value == 7027) {
                    East = true;
North = true;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 7028) {
                    East = true;
North = true;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 7029) {
                    East = true;
North = true;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 7030) {
                    East = true;
North = true;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 7031) {
                    East = true;
North = true;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 7032) {
                    East = true;
North = true;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 7033) {
                    East = true;
North = true;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 7034) {
                    East = true;
North = true;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 7035) {
                    East = true;
North = false;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 7036) {
                    East = true;
North = false;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 7037) {
                    East = true;
North = false;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 7038) {
                    East = true;
North = false;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 7039) {
                    East = true;
North = false;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 7040) {
                    East = true;
North = false;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 7041) {
                    East = true;
North = false;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 7042) {
                    East = true;
North = false;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 7043) {
                    East = false;
North = true;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 7044) {
                    East = false;
North = true;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 7045) {
                    East = false;
North = true;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 7046) {
                    East = false;
North = true;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 7047) {
                    East = false;
North = true;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 7048) {
                    East = false;
North = true;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 7049) {
                    East = false;
North = true;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 7050) {
                    East = false;
North = true;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 7051) {
                    East = false;
North = false;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 7052) {
                    East = false;
North = false;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 7053) {
                    East = false;
North = false;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 7054) {
                    East = false;
North = false;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 7055) {
                    East = false;
North = false;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 7056) {
                    East = false;
North = false;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 7057) {
                    East = false;
North = false;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 7058) {
                    East = false;
North = false;
South = false;
Waterlogged = false;
West = false;
                }

            }
        }

        public bool East { get; set; } = false;
        public bool North { get; set; } = false;
        public bool South { get; set; } = false;
        public bool Waterlogged { get; set; } = false;
        public bool West { get; set; } = false;

        public BlockLimeStainedGlassPane() {
            State = DefaultState;
        }

        public BlockLimeStainedGlassPane(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockLimeStainedGlassPane(bool east, bool north, bool south, bool waterlogged, bool west) {
            East = east;
            North = north;
            South = south;
            Waterlogged = waterlogged;
            West = west;
        }
    }
}