// FILE AUTOGENERATED. DO NOT MODIFY
namespace nylium.Core.Item.Items {

    [Item("minecraft:light_blue_glazed_terracotta", 451, 64, 529)]
    public class ItemLightBlueGlazedTerracotta : BlockItem { }
}