// FILE AUTOGENERATED. DO NOT MODIFY
namespace nylium.Core.Item.Items {

    [Item("minecraft:infested_cracked_stone_bricks", 238, 64, 236)]
    public class ItemInfestedCrackedStoneBricks : BlockItem { }
}