// FILE AUTOGENERATED. DO NOT MODIFY
namespace nylium.Core.Item.Items {

    [Item("minecraft:zombified_piglin_spawn_egg", 822, 64)]
    public class ItemZombifiedPiglinSpawnEgg : BlockItem { }
}