// FILE AUTOGENERATED. DO NOT MODIFY
namespace nylium.Core.Item.Items {

    [Item("minecraft:smooth_red_sandstone_slab", 544, 64, 642)]
    public class ItemSmoothRedSandstoneSlab : BlockItem { }
}