// FILE AUTOGENERATED. DO NOT MODIFY
namespace nylium.Core.Item.Items {

    [Item("minecraft:polished_blackstone_stairs", 969, 64, 755)]
    public class ItemPolishedBlackstoneStairs : BlockItem { }
}