// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:tnt", 137, 1430, 1431, 1431)]
    public class BlockTnt : BlockBase {

        public override ushort State {
            get {
                if(Unstable == true) {
                    return 1430;
                }

                if(Unstable == false) {
                    return 1431;
                }

                return DefaultState;
            }

            set {
                if(value == 1430) {
                    Unstable = true;
                }

                if(value == 1431) {
                    Unstable = false;
                }

            }
        }

        public bool Unstable { get; set; } = false;

        public BlockTnt() {
            State = DefaultState;
        }

        public BlockTnt(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockTnt(bool unstable) {
            Unstable = unstable;
        }
    }
}