// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:warped_pressure_plate", 709, 15069, 15070, 15070)]
    public class BlockWarpedPressurePlate : BlockBase {

        public override ushort State {
            get {
                if(Powered == true) {
                    return 15069;
                }

                if(Powered == false) {
                    return 15070;
                }

                return DefaultState;
            }

            set {
                if(value == 15069) {
                    Powered = true;
                }

                if(value == 15070) {
                    Powered = false;
                }

            }
        }

        public bool Powered { get; set; } = false;

        public BlockWarpedPressurePlate() {
            State = DefaultState;
        }

        public BlockWarpedPressurePlate(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockWarpedPressurePlate(bool powered) {
            Powered = powered;
        }
    }
}