// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:glass_pane", 243, 4735, 4766, 4766)]
    public class BlockGlassPane : BlockBase {

        public override ushort State {
            get {
                if(East == true && North == true && South == true && Waterlogged == true && West == true) {
                    return 4735;
                }

                if(East == true && North == true && South == true && Waterlogged == true && West == false) {
                    return 4736;
                }

                if(East == true && North == true && South == true && Waterlogged == false && West == true) {
                    return 4737;
                }

                if(East == true && North == true && South == true && Waterlogged == false && West == false) {
                    return 4738;
                }

                if(East == true && North == true && South == false && Waterlogged == true && West == true) {
                    return 4739;
                }

                if(East == true && North == true && South == false && Waterlogged == true && West == false) {
                    return 4740;
                }

                if(East == true && North == true && South == false && Waterlogged == false && West == true) {
                    return 4741;
                }

                if(East == true && North == true && South == false && Waterlogged == false && West == false) {
                    return 4742;
                }

                if(East == true && North == false && South == true && Waterlogged == true && West == true) {
                    return 4743;
                }

                if(East == true && North == false && South == true && Waterlogged == true && West == false) {
                    return 4744;
                }

                if(East == true && North == false && South == true && Waterlogged == false && West == true) {
                    return 4745;
                }

                if(East == true && North == false && South == true && Waterlogged == false && West == false) {
                    return 4746;
                }

                if(East == true && North == false && South == false && Waterlogged == true && West == true) {
                    return 4747;
                }

                if(East == true && North == false && South == false && Waterlogged == true && West == false) {
                    return 4748;
                }

                if(East == true && North == false && South == false && Waterlogged == false && West == true) {
                    return 4749;
                }

                if(East == true && North == false && South == false && Waterlogged == false && West == false) {
                    return 4750;
                }

                if(East == false && North == true && South == true && Waterlogged == true && West == true) {
                    return 4751;
                }

                if(East == false && North == true && South == true && Waterlogged == true && West == false) {
                    return 4752;
                }

                if(East == false && North == true && South == true && Waterlogged == false && West == true) {
                    return 4753;
                }

                if(East == false && North == true && South == true && Waterlogged == false && West == false) {
                    return 4754;
                }

                if(East == false && North == true && South == false && Waterlogged == true && West == true) {
                    return 4755;
                }

                if(East == false && North == true && South == false && Waterlogged == true && West == false) {
                    return 4756;
                }

                if(East == false && North == true && South == false && Waterlogged == false && West == true) {
                    return 4757;
                }

                if(East == false && North == true && South == false && Waterlogged == false && West == false) {
                    return 4758;
                }

                if(East == false && North == false && South == true && Waterlogged == true && West == true) {
                    return 4759;
                }

                if(East == false && North == false && South == true && Waterlogged == true && West == false) {
                    return 4760;
                }

                if(East == false && North == false && South == true && Waterlogged == false && West == true) {
                    return 4761;
                }

                if(East == false && North == false && South == true && Waterlogged == false && West == false) {
                    return 4762;
                }

                if(East == false && North == false && South == false && Waterlogged == true && West == true) {
                    return 4763;
                }

                if(East == false && North == false && South == false && Waterlogged == true && West == false) {
                    return 4764;
                }

                if(East == false && North == false && South == false && Waterlogged == false && West == true) {
                    return 4765;
                }

                if(East == false && North == false && South == false && Waterlogged == false && West == false) {
                    return 4766;
                }

                return DefaultState;
            }

            set {
                if(value == 4735) {
                    East = true;
North = true;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 4736) {
                    East = true;
North = true;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 4737) {
                    East = true;
North = true;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 4738) {
                    East = true;
North = true;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 4739) {
                    East = true;
North = true;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 4740) {
                    East = true;
North = true;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 4741) {
                    East = true;
North = true;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 4742) {
                    East = true;
North = true;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 4743) {
                    East = true;
North = false;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 4744) {
                    East = true;
North = false;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 4745) {
                    East = true;
North = false;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 4746) {
                    East = true;
North = false;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 4747) {
                    East = true;
North = false;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 4748) {
                    East = true;
North = false;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 4749) {
                    East = true;
North = false;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 4750) {
                    East = true;
North = false;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 4751) {
                    East = false;
North = true;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 4752) {
                    East = false;
North = true;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 4753) {
                    East = false;
North = true;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 4754) {
                    East = false;
North = true;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 4755) {
                    East = false;
North = true;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 4756) {
                    East = false;
North = true;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 4757) {
                    East = false;
North = true;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 4758) {
                    East = false;
North = true;
South = false;
Waterlogged = false;
West = false;
                }

                if(value == 4759) {
                    East = false;
North = false;
South = true;
Waterlogged = true;
West = true;
                }

                if(value == 4760) {
                    East = false;
North = false;
South = true;
Waterlogged = true;
West = false;
                }

                if(value == 4761) {
                    East = false;
North = false;
South = true;
Waterlogged = false;
West = true;
                }

                if(value == 4762) {
                    East = false;
North = false;
South = true;
Waterlogged = false;
West = false;
                }

                if(value == 4763) {
                    East = false;
North = false;
South = false;
Waterlogged = true;
West = true;
                }

                if(value == 4764) {
                    East = false;
North = false;
South = false;
Waterlogged = true;
West = false;
                }

                if(value == 4765) {
                    East = false;
North = false;
South = false;
Waterlogged = false;
West = true;
                }

                if(value == 4766) {
                    East = false;
North = false;
South = false;
Waterlogged = false;
West = false;
                }

            }
        }

        public bool East { get; set; } = false;
        public bool North { get; set; } = false;
        public bool South { get; set; } = false;
        public bool Waterlogged { get; set; } = false;
        public bool West { get; set; } = false;

        public BlockGlassPane() {
            State = DefaultState;
        }

        public BlockGlassPane(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockGlassPane(bool east, bool north, bool south, bool waterlogged, bool west) {
            East = east;
            North = north;
            South = south;
            Waterlogged = waterlogged;
            West = west;
        }
    }
}