// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:jungle_button", 311, 6422, 6445, 6431)]
    public class BlockJungleButton : BlockBase {

        public override ushort State {
            get {
                if(Face == "floor" && Facing == "north" && Powered == true) {
                    return 6422;
                }

                if(Face == "floor" && Facing == "north" && Powered == false) {
                    return 6423;
                }

                if(Face == "floor" && Facing == "south" && Powered == true) {
                    return 6424;
                }

                if(Face == "floor" && Facing == "south" && Powered == false) {
                    return 6425;
                }

                if(Face == "floor" && Facing == "west" && Powered == true) {
                    return 6426;
                }

                if(Face == "floor" && Facing == "west" && Powered == false) {
                    return 6427;
                }

                if(Face == "floor" && Facing == "east" && Powered == true) {
                    return 6428;
                }

                if(Face == "floor" && Facing == "east" && Powered == false) {
                    return 6429;
                }

                if(Face == "wall" && Facing == "north" && Powered == true) {
                    return 6430;
                }

                if(Face == "wall" && Facing == "north" && Powered == false) {
                    return 6431;
                }

                if(Face == "wall" && Facing == "south" && Powered == true) {
                    return 6432;
                }

                if(Face == "wall" && Facing == "south" && Powered == false) {
                    return 6433;
                }

                if(Face == "wall" && Facing == "west" && Powered == true) {
                    return 6434;
                }

                if(Face == "wall" && Facing == "west" && Powered == false) {
                    return 6435;
                }

                if(Face == "wall" && Facing == "east" && Powered == true) {
                    return 6436;
                }

                if(Face == "wall" && Facing == "east" && Powered == false) {
                    return 6437;
                }

                if(Face == "ceiling" && Facing == "north" && Powered == true) {
                    return 6438;
                }

                if(Face == "ceiling" && Facing == "north" && Powered == false) {
                    return 6439;
                }

                if(Face == "ceiling" && Facing == "south" && Powered == true) {
                    return 6440;
                }

                if(Face == "ceiling" && Facing == "south" && Powered == false) {
                    return 6441;
                }

                if(Face == "ceiling" && Facing == "west" && Powered == true) {
                    return 6442;
                }

                if(Face == "ceiling" && Facing == "west" && Powered == false) {
                    return 6443;
                }

                if(Face == "ceiling" && Facing == "east" && Powered == true) {
                    return 6444;
                }

                if(Face == "ceiling" && Facing == "east" && Powered == false) {
                    return 6445;
                }

                return DefaultState;
            }

            set {
                if(value == 6422) {
                    Face = "floor";
Facing = "north";
Powered = true;
                }

                if(value == 6423) {
                    Face = "floor";
Facing = "north";
Powered = false;
                }

                if(value == 6424) {
                    Face = "floor";
Facing = "south";
Powered = true;
                }

                if(value == 6425) {
                    Face = "floor";
Facing = "south";
Powered = false;
                }

                if(value == 6426) {
                    Face = "floor";
Facing = "west";
Powered = true;
                }

                if(value == 6427) {
                    Face = "floor";
Facing = "west";
Powered = false;
                }

                if(value == 6428) {
                    Face = "floor";
Facing = "east";
Powered = true;
                }

                if(value == 6429) {
                    Face = "floor";
Facing = "east";
Powered = false;
                }

                if(value == 6430) {
                    Face = "wall";
Facing = "north";
Powered = true;
                }

                if(value == 6431) {
                    Face = "wall";
Facing = "north";
Powered = false;
                }

                if(value == 6432) {
                    Face = "wall";
Facing = "south";
Powered = true;
                }

                if(value == 6433) {
                    Face = "wall";
Facing = "south";
Powered = false;
                }

                if(value == 6434) {
                    Face = "wall";
Facing = "west";
Powered = true;
                }

                if(value == 6435) {
                    Face = "wall";
Facing = "west";
Powered = false;
                }

                if(value == 6436) {
                    Face = "wall";
Facing = "east";
Powered = true;
                }

                if(value == 6437) {
                    Face = "wall";
Facing = "east";
Powered = false;
                }

                if(value == 6438) {
                    Face = "ceiling";
Facing = "north";
Powered = true;
                }

                if(value == 6439) {
                    Face = "ceiling";
Facing = "north";
Powered = false;
                }

                if(value == 6440) {
                    Face = "ceiling";
Facing = "south";
Powered = true;
                }

                if(value == 6441) {
                    Face = "ceiling";
Facing = "south";
Powered = false;
                }

                if(value == 6442) {
                    Face = "ceiling";
Facing = "west";
Powered = true;
                }

                if(value == 6443) {
                    Face = "ceiling";
Facing = "west";
Powered = false;
                }

                if(value == 6444) {
                    Face = "ceiling";
Facing = "east";
Powered = true;
                }

                if(value == 6445) {
                    Face = "ceiling";
Facing = "east";
Powered = false;
                }

            }
        }

        public string Face { get; set; } = "wall";
        public string Facing { get; set; } = "north";
        public bool Powered { get; set; } = false;

        public BlockJungleButton() {
            State = DefaultState;
        }

        public BlockJungleButton(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockJungleButton(string face, string facing, bool powered) {
            Face = face;
            Facing = facing;
            Powered = powered;
        }
    }
}