// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:barrel", 668, 14795, 14806, 14796)]
    public class BlockBarrel : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north" && Open == true) {
                    return 14795;
                }

                if(Facing == "north" && Open == false) {
                    return 14796;
                }

                if(Facing == "east" && Open == true) {
                    return 14797;
                }

                if(Facing == "east" && Open == false) {
                    return 14798;
                }

                if(Facing == "south" && Open == true) {
                    return 14799;
                }

                if(Facing == "south" && Open == false) {
                    return 14800;
                }

                if(Facing == "west" && Open == true) {
                    return 14801;
                }

                if(Facing == "west" && Open == false) {
                    return 14802;
                }

                if(Facing == "up" && Open == true) {
                    return 14803;
                }

                if(Facing == "up" && Open == false) {
                    return 14804;
                }

                if(Facing == "down" && Open == true) {
                    return 14805;
                }

                if(Facing == "down" && Open == false) {
                    return 14806;
                }

                return DefaultState;
            }

            set {
                if(value == 14795) {
                    Facing = "north";
Open = true;
                }

                if(value == 14796) {
                    Facing = "north";
Open = false;
                }

                if(value == 14797) {
                    Facing = "east";
Open = true;
                }

                if(value == 14798) {
                    Facing = "east";
Open = false;
                }

                if(value == 14799) {
                    Facing = "south";
Open = true;
                }

                if(value == 14800) {
                    Facing = "south";
Open = false;
                }

                if(value == 14801) {
                    Facing = "west";
Open = true;
                }

                if(value == 14802) {
                    Facing = "west";
Open = false;
                }

                if(value == 14803) {
                    Facing = "up";
Open = true;
                }

                if(value == 14804) {
                    Facing = "up";
Open = false;
                }

                if(value == 14805) {
                    Facing = "down";
Open = true;
                }

                if(value == 14806) {
                    Facing = "down";
Open = false;
                }

            }
        }

        public string Facing { get; set; } = "north";
        public bool Open { get; set; } = false;

        public BlockBarrel() {
            State = DefaultState;
        }

        public BlockBarrel(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockBarrel(string facing, bool open) {
            Facing = facing;
            Open = open;
        }
    }
}