// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:white_glazed_terracotta", 526, 9378, 9381, 9378)]
    public class BlockWhiteGlazedTerracotta : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9378;
                }

                if(Facing == "south") {
                    return 9379;
                }

                if(Facing == "west") {
                    return 9380;
                }

                if(Facing == "east") {
                    return 9381;
                }

                return DefaultState;
            }

            set {
                if(value == 9378) {
                    Facing = "north";
                }

                if(value == 9379) {
                    Facing = "south";
                }

                if(value == 9380) {
                    Facing = "west";
                }

                if(value == 9381) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockWhiteGlazedTerracotta() {
            State = DefaultState;
        }

        public BlockWhiteGlazedTerracotta(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockWhiteGlazedTerracotta(string facing) {
            Facing = facing;
        }
    }
}