// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:cracked_stone_bricks", 230, 4497, 4497, 4497)]
    public class BlockCrackedStoneBricks : BlockBase {

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockCrackedStoneBricks() {
            State = DefaultState;
        }

        public BlockCrackedStoneBricks(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}