// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:light_blue_wall_banner", 435, 8169, 8172, 8169)]
    public class BlockLightBlueWallBanner : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 8169;
                }

                if(Facing == "south") {
                    return 8170;
                }

                if(Facing == "west") {
                    return 8171;
                }

                if(Facing == "east") {
                    return 8172;
                }

                return DefaultState;
            }

            set {
                if(value == 8169) {
                    Facing = "north";
                }

                if(value == 8170) {
                    Facing = "south";
                }

                if(value == 8171) {
                    Facing = "west";
                }

                if(value == 8172) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockLightBlueWallBanner() {
            State = DefaultState;
        }

        public BlockLightBlueWallBanner(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockLightBlueWallBanner(string facing) {
            Facing = facing;
        }
    }
}