// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:nether_portal", 201, 4014, 4015, 4014)]
    public class BlockNetherPortal : BlockBase {

        public override ushort State {
            get {
                if(Axis == "x") {
                    return 4014;
                }

                if(Axis == "z") {
                    return 4015;
                }

                return DefaultState;
            }

            set {
                if(value == 4014) {
                    Axis = "x";
                }

                if(value == 4015) {
                    Axis = "z";
                }

            }
        }

        public string Axis { get; set; } = "x";

        public BlockNetherPortal() {
            State = DefaultState;
        }

        public BlockNetherPortal(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockNetherPortal(string axis) {
            Axis = axis;
        }
    }
}