// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:lime_glazed_terracotta", 531, 9398, 9401, 9398)]
    public class BlockLimeGlazedTerracotta : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9398;
                }

                if(Facing == "south") {
                    return 9399;
                }

                if(Facing == "west") {
                    return 9400;
                }

                if(Facing == "east") {
                    return 9401;
                }

                return DefaultState;
            }

            set {
                if(value == 9398) {
                    Facing = "north";
                }

                if(value == 9399) {
                    Facing = "south";
                }

                if(value == 9400) {
                    Facing = "west";
                }

                if(value == 9401) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockLimeGlazedTerracotta() {
            State = DefaultState;
        }

        public BlockLimeGlazedTerracotta(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockLimeGlazedTerracotta(string facing) {
            Facing = facing;
        }
    }
}