// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:potted_red_mushroom", 302, 6330, 6330, 6330)]
    public class BlockPottedRedMushroom : BlockBase {

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockPottedRedMushroom() {
            State = DefaultState;
        }

        public BlockPottedRedMushroom(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}