// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:white_wall_banner", 432, 8157, 8160, 8157)]
    public class BlockWhiteWallBanner : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 8157;
                }

                if(Facing == "south") {
                    return 8158;
                }

                if(Facing == "west") {
                    return 8159;
                }

                if(Facing == "east") {
                    return 8160;
                }

                return DefaultState;
            }

            set {
                if(value == 8157) {
                    Facing = "north";
                }

                if(value == 8158) {
                    Facing = "south";
                }

                if(value == 8159) {
                    Facing = "west";
                }

                if(value == 8160) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockWhiteWallBanner() {
            State = DefaultState;
        }

        public BlockWhiteWallBanner(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockWhiteWallBanner(string facing) {
            Facing = facing;
        }
    }
}