// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    [Block("minecraft:gray_glazed_terracotta", 533, 9406, 9409, 9406)]
    public class BlockGrayGlazedTerracotta : BlockBase {

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9406;
                }

                if(Facing == "south") {
                    return 9407;
                }

                if(Facing == "west") {
                    return 9408;
                }

                if(Facing == "east") {
                    return 9409;
                }

                return DefaultState;
            }

            set {
                if(value == 9406) {
                    Facing = "north";
                }

                if(value == 9407) {
                    Facing = "south";
                }

                if(value == 9408) {
                    Facing = "west";
                }

                if(value == 9409) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockGrayGlazedTerracotta() {
            State = DefaultState;
        }

        public BlockGrayGlazedTerracotta(ushort state) : base(state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockGrayGlazedTerracotta(string facing) {
            Facing = facing;
        }
    }
}