// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BrownWoolBlock : BaseBlock {

        public BrownWoolBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 114, 1396) { }
    }
}
