// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class GrindstoneBlock : BaseBlock {

        public Face Face { get; }
        public Face Facing { get; }

        public GrindstoneBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 673, 14829) { }

        public GrindstoneBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 673, state) {
            if(state == 14825) {
                Face = Face.Floor;
                Facing = Face.North;
            } else if(state == 14826) {
                Face = Face.Floor;
                Facing = Face.South;
            } else if(state == 14827) {
                Face = Face.Floor;
                Facing = Face.West;
            } else if(state == 14828) {
                Face = Face.Floor;
                Facing = Face.East;
            } else if(state == 14829) {
                Face = Face.Wall;
                Facing = Face.North;
            } else if(state == 14830) {
                Face = Face.Wall;
                Facing = Face.South;
            } else if(state == 14831) {
                Face = Face.Wall;
                Facing = Face.West;
            } else if(state == 14832) {
                Face = Face.Wall;
                Facing = Face.East;
            } else if(state == 14833) {
                Face = Face.Ceiling;
                Facing = Face.North;
            } else if(state == 14834) {
                Face = Face.Ceiling;
                Facing = Face.South;
            } else if(state == 14835) {
                Face = Face.Ceiling;
                Facing = Face.West;
            } else if(state == 14836) {
                Face = Face.Ceiling;
                Facing = Face.East;
            }
        }

        public GrindstoneBlock(Chunk chunk, int x, int y, int z, Face face, Face facing) : base(chunk, x, y, z, 673, 14829) {
if(face == Face.Floor && facing == Face.North) {
                State = 14825;
            } else if(face == Face.Floor && facing == Face.South) {
                State = 14826;
            } else if(face == Face.Floor && facing == Face.West) {
                State = 14827;
            } else if(face == Face.Floor && facing == Face.East) {
                State = 14828;
            } else if(face == Face.Wall && facing == Face.North) {
                State = 14829;
            } else if(face == Face.Wall && facing == Face.South) {
                State = 14830;
            } else if(face == Face.Wall && facing == Face.West) {
                State = 14831;
            } else if(face == Face.Wall && facing == Face.East) {
                State = 14832;
            } else if(face == Face.Ceiling && facing == Face.North) {
                State = 14833;
            } else if(face == Face.Ceiling && facing == Face.South) {
                State = 14834;
            } else if(face == Face.Ceiling && facing == Face.West) {
                State = 14835;
            } else if(face == Face.Ceiling && facing == Face.East) {
                State = 14836;
            }
        }
    }
}
