// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class IronBarsBlock : BaseBlock {

        public bool East { get; }
        public bool North { get; }
        public bool South { get; }
        public bool Waterlogged { get; }
        public bool West { get; }

        public IronBarsBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 241, 4728) { }

        public IronBarsBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 241, state) {
            if(state == 4697) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 4698) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 4699) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 4700) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 4701) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 4702) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 4703) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 4704) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 4705) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 4706) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 4707) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 4708) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 4709) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 4710) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 4711) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 4712) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 4713) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 4714) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 4715) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 4716) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 4717) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 4718) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 4719) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 4720) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 4721) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 4722) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 4723) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 4724) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 4725) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 4726) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 4727) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 4728) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            }
        }

        public IronBarsBlock(Chunk chunk, int x, int y, int z, bool east, bool north, bool south, bool waterlogged, bool west) : base(chunk, x, y, z, 241, 4728) {
if(east == true && north == true && south == true && waterlogged == true && west == true) {
                State = 4697;
            } else if(east == true && north == true && south == true && waterlogged == true && west == false) {
                State = 4698;
            } else if(east == true && north == true && south == true && waterlogged == false && west == true) {
                State = 4699;
            } else if(east == true && north == true && south == true && waterlogged == false && west == false) {
                State = 4700;
            } else if(east == true && north == true && south == false && waterlogged == true && west == true) {
                State = 4701;
            } else if(east == true && north == true && south == false && waterlogged == true && west == false) {
                State = 4702;
            } else if(east == true && north == true && south == false && waterlogged == false && west == true) {
                State = 4703;
            } else if(east == true && north == true && south == false && waterlogged == false && west == false) {
                State = 4704;
            } else if(east == true && north == false && south == true && waterlogged == true && west == true) {
                State = 4705;
            } else if(east == true && north == false && south == true && waterlogged == true && west == false) {
                State = 4706;
            } else if(east == true && north == false && south == true && waterlogged == false && west == true) {
                State = 4707;
            } else if(east == true && north == false && south == true && waterlogged == false && west == false) {
                State = 4708;
            } else if(east == true && north == false && south == false && waterlogged == true && west == true) {
                State = 4709;
            } else if(east == true && north == false && south == false && waterlogged == true && west == false) {
                State = 4710;
            } else if(east == true && north == false && south == false && waterlogged == false && west == true) {
                State = 4711;
            } else if(east == true && north == false && south == false && waterlogged == false && west == false) {
                State = 4712;
            } else if(east == false && north == true && south == true && waterlogged == true && west == true) {
                State = 4713;
            } else if(east == false && north == true && south == true && waterlogged == true && west == false) {
                State = 4714;
            } else if(east == false && north == true && south == true && waterlogged == false && west == true) {
                State = 4715;
            } else if(east == false && north == true && south == true && waterlogged == false && west == false) {
                State = 4716;
            } else if(east == false && north == true && south == false && waterlogged == true && west == true) {
                State = 4717;
            } else if(east == false && north == true && south == false && waterlogged == true && west == false) {
                State = 4718;
            } else if(east == false && north == true && south == false && waterlogged == false && west == true) {
                State = 4719;
            } else if(east == false && north == true && south == false && waterlogged == false && west == false) {
                State = 4720;
            } else if(east == false && north == false && south == true && waterlogged == true && west == true) {
                State = 4721;
            } else if(east == false && north == false && south == true && waterlogged == true && west == false) {
                State = 4722;
            } else if(east == false && north == false && south == true && waterlogged == false && west == true) {
                State = 4723;
            } else if(east == false && north == false && south == true && waterlogged == false && west == false) {
                State = 4724;
            } else if(east == false && north == false && south == false && waterlogged == true && west == true) {
                State = 4725;
            } else if(east == false && north == false && south == false && waterlogged == true && west == false) {
                State = 4726;
            } else if(east == false && north == false && south == false && waterlogged == false && west == true) {
                State = 4727;
            } else if(east == false && north == false && south == false && waterlogged == false && west == false) {
                State = 4728;
            }
        }
    }
}
