// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockBubbleCoralBlock : BlockBase {

        public override string Id { get { return "minecraft:bubble_coral_block"; } }

        public override ushort MinimumState { get { return 9521; } }
        public override ushort MaximumState { get { return 9521; } }
        public override ushort DefaultState { get { return 9521; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockBubbleCoralBlock() {
            State = DefaultState;
        }

        public BlockBubbleCoralBlock(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}