// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockBlackConcretePowder : BlockBase {

        public override string Id { get { return "minecraft:black_concrete_powder"; } }

        public override ushort MinimumState { get { return 9473; } }
        public override ushort MaximumState { get { return 9473; } }
        public override ushort DefaultState { get { return 9473; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockBlackConcretePowder() {
            State = DefaultState;
        }

        public BlockBlackConcretePowder(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}