// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockStrippedAcaciaWood : BlockBase {

        public override string Id { get { return "minecraft:stripped_acacia_wood"; } }

        public override ushort MinimumState { get { return 139; } }
        public override ushort MaximumState { get { return 141; } }
        public override ushort DefaultState { get { return 140; } }

        public override ushort State {
            get {
                if(Axis == "x") {
                    return 139;
                }

                if(Axis == "y") {
                    return 140;
                }

                if(Axis == "z") {
                    return 141;
                }

                return DefaultState;
            }

            set {
                if(value == 139) {
                    Axis = "x";
                }

                if(value == 140) {
                    Axis = "y";
                }

                if(value == 141) {
                    Axis = "z";
                }

            }
        }

        public string Axis { get; set; } = "y";

        public BlockStrippedAcaciaWood() {
            State = DefaultState;
        }

        public BlockStrippedAcaciaWood(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockStrippedAcaciaWood(string axis) {
            Axis = axis;
        }
    }
}