// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockBlueWool : BlockBase {

        public override string Id { get { return "minecraft:blue_wool"; } }

        public override ushort MinimumState { get { return 1395; } }
        public override ushort MaximumState { get { return 1395; } }
        public override ushort DefaultState { get { return 1395; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockBlueWool() {
            State = DefaultState;
        }

        public BlockBlueWool(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}