// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockAcaciaSapling : BlockBase {

        public override string Id { get { return "minecraft:acacia_sapling"; } }

        public override ushort MinimumState { get { return 29; } }
        public override ushort MaximumState { get { return 30; } }
        public override ushort DefaultState { get { return 29; } }

        public override ushort State {
            get {
                if(Stage == 0) {
                    return 29;
                }

                if(Stage == 1) {
                    return 30;
                }

                return DefaultState;
            }

            set {
                if(value == 29) {
                    Stage = 0;
                }

                if(value == 30) {
                    Stage = 1;
                }

            }
        }

        public int Stage { get; set; } = 0;

        public BlockAcaciaSapling() {
            State = DefaultState;
        }

        public BlockAcaciaSapling(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockAcaciaSapling(int stage) {
            Stage = stage;
        }
    }
}