// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockRepeatingCommandBlock : BlockBase {

        public override string Id { get { return "minecraft:repeating_command_block"; } }

        public override ushort MinimumState { get { return 9229; } }
        public override ushort MaximumState { get { return 9240; } }
        public override ushort DefaultState { get { return 9235; } }

        public override ushort State {
            get {
                if(Conditional == true && Facing == "north") {
                    return 9229;
                }

                if(Conditional == true && Facing == "east") {
                    return 9230;
                }

                if(Conditional == true && Facing == "south") {
                    return 9231;
                }

                if(Conditional == true && Facing == "west") {
                    return 9232;
                }

                if(Conditional == true && Facing == "up") {
                    return 9233;
                }

                if(Conditional == true && Facing == "down") {
                    return 9234;
                }

                if(Conditional == false && Facing == "north") {
                    return 9235;
                }

                if(Conditional == false && Facing == "east") {
                    return 9236;
                }

                if(Conditional == false && Facing == "south") {
                    return 9237;
                }

                if(Conditional == false && Facing == "west") {
                    return 9238;
                }

                if(Conditional == false && Facing == "up") {
                    return 9239;
                }

                if(Conditional == false && Facing == "down") {
                    return 9240;
                }

                return DefaultState;
            }

            set {
                if(value == 9229) {
                    Conditional = true;
Facing = "north";
                }

                if(value == 9230) {
                    Conditional = true;
Facing = "east";
                }

                if(value == 9231) {
                    Conditional = true;
Facing = "south";
                }

                if(value == 9232) {
                    Conditional = true;
Facing = "west";
                }

                if(value == 9233) {
                    Conditional = true;
Facing = "up";
                }

                if(value == 9234) {
                    Conditional = true;
Facing = "down";
                }

                if(value == 9235) {
                    Conditional = false;
Facing = "north";
                }

                if(value == 9236) {
                    Conditional = false;
Facing = "east";
                }

                if(value == 9237) {
                    Conditional = false;
Facing = "south";
                }

                if(value == 9238) {
                    Conditional = false;
Facing = "west";
                }

                if(value == 9239) {
                    Conditional = false;
Facing = "up";
                }

                if(value == 9240) {
                    Conditional = false;
Facing = "down";
                }

            }
        }

        public bool Conditional { get; set; } = false;
        public string Facing { get; set; } = "north";

        public BlockRepeatingCommandBlock() {
            State = DefaultState;
        }

        public BlockRepeatingCommandBlock(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockRepeatingCommandBlock(bool conditional, string facing) {
            Conditional = conditional;
            Facing = facing;
        }
    }
}