// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockLadder : BlockBase {

        public override string Id { get { return "minecraft:ladder"; } }

        public override ushort MinimumState { get { return 3637; } }
        public override ushort MaximumState { get { return 3644; } }
        public override ushort DefaultState { get { return 3638; } }

        public override ushort State {
            get {
                if(Facing == "north" && Waterlogged == true) {
                    return 3637;
                }

                if(Facing == "north" && Waterlogged == false) {
                    return 3638;
                }

                if(Facing == "south" && Waterlogged == true) {
                    return 3639;
                }

                if(Facing == "south" && Waterlogged == false) {
                    return 3640;
                }

                if(Facing == "west" && Waterlogged == true) {
                    return 3641;
                }

                if(Facing == "west" && Waterlogged == false) {
                    return 3642;
                }

                if(Facing == "east" && Waterlogged == true) {
                    return 3643;
                }

                if(Facing == "east" && Waterlogged == false) {
                    return 3644;
                }

                return DefaultState;
            }

            set {
                if(value == 3637) {
                    Facing = "north";
Waterlogged = true;
                }

                if(value == 3638) {
                    Facing = "north";
Waterlogged = false;
                }

                if(value == 3639) {
                    Facing = "south";
Waterlogged = true;
                }

                if(value == 3640) {
                    Facing = "south";
Waterlogged = false;
                }

                if(value == 3641) {
                    Facing = "west";
Waterlogged = true;
                }

                if(value == 3642) {
                    Facing = "west";
Waterlogged = false;
                }

                if(value == 3643) {
                    Facing = "east";
Waterlogged = true;
                }

                if(value == 3644) {
                    Facing = "east";
Waterlogged = false;
                }

            }
        }

        public string Facing { get; set; } = "north";
        public bool Waterlogged { get; set; } = false;

        public BlockLadder() {
            State = DefaultState;
        }

        public BlockLadder(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockLadder(string facing, bool waterlogged) {
            Facing = facing;
            Waterlogged = waterlogged;
        }
    }
}