// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockCyanShulkerBox : BlockBase {

        public override string Id { get { return "minecraft:cyan_shulker_box"; } }

        public override ushort MinimumState { get { return 9336; } }
        public override ushort MaximumState { get { return 9341; } }
        public override ushort DefaultState { get { return 9340; } }

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9336;
                }

                if(Facing == "east") {
                    return 9337;
                }

                if(Facing == "south") {
                    return 9338;
                }

                if(Facing == "west") {
                    return 9339;
                }

                if(Facing == "up") {
                    return 9340;
                }

                if(Facing == "down") {
                    return 9341;
                }

                return DefaultState;
            }

            set {
                if(value == 9336) {
                    Facing = "north";
                }

                if(value == 9337) {
                    Facing = "east";
                }

                if(value == 9338) {
                    Facing = "south";
                }

                if(value == 9339) {
                    Facing = "west";
                }

                if(value == 9340) {
                    Facing = "up";
                }

                if(value == 9341) {
                    Facing = "down";
                }

            }
        }

        public string Facing { get; set; } = "up";

        public BlockCyanShulkerBox() {
            State = DefaultState;
        }

        public BlockCyanShulkerBox(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockCyanShulkerBox(string facing) {
            Facing = facing;
        }
    }
}