// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockLightBlueWallBanner : BlockBase {

        public override string Id { get { return "minecraft:light_blue_wall_banner"; } }

        public override ushort MinimumState { get { return 8169; } }
        public override ushort MaximumState { get { return 8172; } }
        public override ushort DefaultState { get { return 8169; } }

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 8169;
                }

                if(Facing == "south") {
                    return 8170;
                }

                if(Facing == "west") {
                    return 8171;
                }

                if(Facing == "east") {
                    return 8172;
                }

                return DefaultState;
            }

            set {
                if(value == 8169) {
                    Facing = "north";
                }

                if(value == 8170) {
                    Facing = "south";
                }

                if(value == 8171) {
                    Facing = "west";
                }

                if(value == 8172) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockLightBlueWallBanner() {
            State = DefaultState;
        }

        public BlockLightBlueWallBanner(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockLightBlueWallBanner(string facing) {
            Facing = facing;
        }
    }
}