// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockCrackedNetherBricks : BlockBase {

        public override string Id { get { return "minecraft:cracked_nether_bricks"; } }

        public override ushort MinimumState { get { return 17110; } }
        public override ushort MaximumState { get { return 17110; } }
        public override ushort DefaultState { get { return 17110; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockCrackedNetherBricks() {
            State = DefaultState;
        }

        public BlockCrackedNetherBricks(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}