// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockCrimsonPressurePlate : BlockBase {

        public override string Id { get { return "minecraft:crimson_pressure_plate"; } }

        public override ushort MinimumState { get { return 15067; } }
        public override ushort MaximumState { get { return 15068; } }
        public override ushort DefaultState { get { return 15068; } }

        public override ushort State {
            get {
                if(Powered == true) {
                    return 15067;
                }

                if(Powered == false) {
                    return 15068;
                }

                return DefaultState;
            }

            set {
                if(value == 15067) {
                    Powered = true;
                }

                if(value == 15068) {
                    Powered = false;
                }

            }
        }

        public bool Powered { get; set; } = false;

        public BlockCrimsonPressurePlate() {
            State = DefaultState;
        }

        public BlockCrimsonPressurePlate(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockCrimsonPressurePlate(bool powered) {
            Powered = powered;
        }
    }
}