// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockDeadHornCoral : BlockBase {

        public override string Id { get { return "minecraft:dead_horn_coral"; } }

        public override ushort MinimumState { get { return 9532; } }
        public override ushort MaximumState { get { return 9533; } }
        public override ushort DefaultState { get { return 9532; } }

        public override ushort State {
            get {
                if(Waterlogged == true) {
                    return 9532;
                }

                if(Waterlogged == false) {
                    return 9533;
                }

                return DefaultState;
            }

            set {
                if(value == 9532) {
                    Waterlogged = true;
                }

                if(value == 9533) {
                    Waterlogged = false;
                }

            }
        }

        public bool Waterlogged { get; set; } = true;

        public BlockDeadHornCoral() {
            State = DefaultState;
        }

        public BlockDeadHornCoral(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockDeadHornCoral(bool waterlogged) {
            Waterlogged = waterlogged;
        }
    }
}