// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockDragonWallHead : BlockBase {

        public override string Id { get { return "minecraft:dragon_wall_head"; } }

        public override ushort MinimumState { get { return 6610; } }
        public override ushort MaximumState { get { return 6613; } }
        public override ushort DefaultState { get { return 6610; } }

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 6610;
                }

                if(Facing == "south") {
                    return 6611;
                }

                if(Facing == "west") {
                    return 6612;
                }

                if(Facing == "east") {
                    return 6613;
                }

                return DefaultState;
            }

            set {
                if(value == 6610) {
                    Facing = "north";
                }

                if(value == 6611) {
                    Facing = "south";
                }

                if(value == 6612) {
                    Facing = "west";
                }

                if(value == 6613) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockDragonWallHead() {
            State = DefaultState;
        }

        public BlockDragonWallHead(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockDragonWallHead(string facing) {
            Facing = facing;
        }
    }
}