// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockOakSapling : BlockBase {

        public override string Id { get { return "minecraft:oak_sapling"; } }

        public override ushort MinimumState { get { return 21; } }
        public override ushort MaximumState { get { return 22; } }
        public override ushort DefaultState { get { return 21; } }

        public override ushort State {
            get {
                if(Stage == 0) {
                    return 21;
                }

                if(Stage == 1) {
                    return 22;
                }

                return DefaultState;
            }

            set {
                if(value == 21) {
                    Stage = 0;
                }

                if(value == 22) {
                    Stage = 1;
                }

            }
        }

        public int Stage { get; set; } = 0;

        public BlockOakSapling() {
            State = DefaultState;
        }

        public BlockOakSapling(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockOakSapling(int stage) {
            Stage = stage;
        }
    }
}