// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockCartographyTable : BlockBase {

        public override string Id { get { return "minecraft:cartography_table"; } }

        public override ushort MinimumState { get { return 14823; } }
        public override ushort MaximumState { get { return 14823; } }
        public override ushort DefaultState { get { return 14823; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockCartographyTable() {
            State = DefaultState;
        }

        public BlockCartographyTable(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}