// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockGreenShulkerBox : BlockBase {

        public override string Id { get { return "minecraft:green_shulker_box"; } }

        public override ushort MinimumState { get { return 9360; } }
        public override ushort MaximumState { get { return 9365; } }
        public override ushort DefaultState { get { return 9364; } }

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 9360;
                }

                if(Facing == "east") {
                    return 9361;
                }

                if(Facing == "south") {
                    return 9362;
                }

                if(Facing == "west") {
                    return 9363;
                }

                if(Facing == "up") {
                    return 9364;
                }

                if(Facing == "down") {
                    return 9365;
                }

                return DefaultState;
            }

            set {
                if(value == 9360) {
                    Facing = "north";
                }

                if(value == 9361) {
                    Facing = "east";
                }

                if(value == 9362) {
                    Facing = "south";
                }

                if(value == 9363) {
                    Facing = "west";
                }

                if(value == 9364) {
                    Facing = "up";
                }

                if(value == 9365) {
                    Facing = "down";
                }

            }
        }

        public string Facing { get; set; } = "up";

        public BlockGreenShulkerBox() {
            State = DefaultState;
        }

        public BlockGreenShulkerBox(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockGreenShulkerBox(string facing) {
            Facing = facing;
        }
    }
}