// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockGreenWallBanner : BlockBase {

        public override string Id { get { return "minecraft:green_wall_banner"; } }

        public override ushort MinimumState { get { return 8209; } }
        public override ushort MaximumState { get { return 8212; } }
        public override ushort DefaultState { get { return 8209; } }

        public override ushort State {
            get {
                if(Facing == "north") {
                    return 8209;
                }

                if(Facing == "south") {
                    return 8210;
                }

                if(Facing == "west") {
                    return 8211;
                }

                if(Facing == "east") {
                    return 8212;
                }

                return DefaultState;
            }

            set {
                if(value == 8209) {
                    Facing = "north";
                }

                if(value == 8210) {
                    Facing = "south";
                }

                if(value == 8211) {
                    Facing = "west";
                }

                if(value == 8212) {
                    Facing = "east";
                }

            }
        }

        public string Facing { get; set; } = "north";

        public BlockGreenWallBanner() {
            State = DefaultState;
        }

        public BlockGreenWallBanner(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockGreenWallBanner(string facing) {
            Facing = facing;
        }
    }
}