// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockWitherRose : BlockBase {

        public override string Id { get { return "minecraft:wither_rose"; } }

        public override ushort MinimumState { get { return 1423; } }
        public override ushort MaximumState { get { return 1423; } }
        public override ushort DefaultState { get { return 1423; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockWitherRose() {
            State = DefaultState;
        }

        public BlockWitherRose(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}