// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockSpruceButton : BlockBase {

        public override string Id { get { return "minecraft:spruce_button"; } }

        public override ushort MinimumState { get { return 6374; } }
        public override ushort MaximumState { get { return 6397; } }
        public override ushort DefaultState { get { return 6383; } }

        public override ushort State {
            get {
                if(Face == "floor" && Facing == "north" && Powered == true) {
                    return 6374;
                }

                if(Face == "floor" && Facing == "north" && Powered == false) {
                    return 6375;
                }

                if(Face == "floor" && Facing == "south" && Powered == true) {
                    return 6376;
                }

                if(Face == "floor" && Facing == "south" && Powered == false) {
                    return 6377;
                }

                if(Face == "floor" && Facing == "west" && Powered == true) {
                    return 6378;
                }

                if(Face == "floor" && Facing == "west" && Powered == false) {
                    return 6379;
                }

                if(Face == "floor" && Facing == "east" && Powered == true) {
                    return 6380;
                }

                if(Face == "floor" && Facing == "east" && Powered == false) {
                    return 6381;
                }

                if(Face == "wall" && Facing == "north" && Powered == true) {
                    return 6382;
                }

                if(Face == "wall" && Facing == "north" && Powered == false) {
                    return 6383;
                }

                if(Face == "wall" && Facing == "south" && Powered == true) {
                    return 6384;
                }

                if(Face == "wall" && Facing == "south" && Powered == false) {
                    return 6385;
                }

                if(Face == "wall" && Facing == "west" && Powered == true) {
                    return 6386;
                }

                if(Face == "wall" && Facing == "west" && Powered == false) {
                    return 6387;
                }

                if(Face == "wall" && Facing == "east" && Powered == true) {
                    return 6388;
                }

                if(Face == "wall" && Facing == "east" && Powered == false) {
                    return 6389;
                }

                if(Face == "ceiling" && Facing == "north" && Powered == true) {
                    return 6390;
                }

                if(Face == "ceiling" && Facing == "north" && Powered == false) {
                    return 6391;
                }

                if(Face == "ceiling" && Facing == "south" && Powered == true) {
                    return 6392;
                }

                if(Face == "ceiling" && Facing == "south" && Powered == false) {
                    return 6393;
                }

                if(Face == "ceiling" && Facing == "west" && Powered == true) {
                    return 6394;
                }

                if(Face == "ceiling" && Facing == "west" && Powered == false) {
                    return 6395;
                }

                if(Face == "ceiling" && Facing == "east" && Powered == true) {
                    return 6396;
                }

                if(Face == "ceiling" && Facing == "east" && Powered == false) {
                    return 6397;
                }

                return DefaultState;
            }

            set {
                if(value == 6374) {
                    Face = "floor";
Facing = "north";
Powered = true;
                }

                if(value == 6375) {
                    Face = "floor";
Facing = "north";
Powered = false;
                }

                if(value == 6376) {
                    Face = "floor";
Facing = "south";
Powered = true;
                }

                if(value == 6377) {
                    Face = "floor";
Facing = "south";
Powered = false;
                }

                if(value == 6378) {
                    Face = "floor";
Facing = "west";
Powered = true;
                }

                if(value == 6379) {
                    Face = "floor";
Facing = "west";
Powered = false;
                }

                if(value == 6380) {
                    Face = "floor";
Facing = "east";
Powered = true;
                }

                if(value == 6381) {
                    Face = "floor";
Facing = "east";
Powered = false;
                }

                if(value == 6382) {
                    Face = "wall";
Facing = "north";
Powered = true;
                }

                if(value == 6383) {
                    Face = "wall";
Facing = "north";
Powered = false;
                }

                if(value == 6384) {
                    Face = "wall";
Facing = "south";
Powered = true;
                }

                if(value == 6385) {
                    Face = "wall";
Facing = "south";
Powered = false;
                }

                if(value == 6386) {
                    Face = "wall";
Facing = "west";
Powered = true;
                }

                if(value == 6387) {
                    Face = "wall";
Facing = "west";
Powered = false;
                }

                if(value == 6388) {
                    Face = "wall";
Facing = "east";
Powered = true;
                }

                if(value == 6389) {
                    Face = "wall";
Facing = "east";
Powered = false;
                }

                if(value == 6390) {
                    Face = "ceiling";
Facing = "north";
Powered = true;
                }

                if(value == 6391) {
                    Face = "ceiling";
Facing = "north";
Powered = false;
                }

                if(value == 6392) {
                    Face = "ceiling";
Facing = "south";
Powered = true;
                }

                if(value == 6393) {
                    Face = "ceiling";
Facing = "south";
Powered = false;
                }

                if(value == 6394) {
                    Face = "ceiling";
Facing = "west";
Powered = true;
                }

                if(value == 6395) {
                    Face = "ceiling";
Facing = "west";
Powered = false;
                }

                if(value == 6396) {
                    Face = "ceiling";
Facing = "east";
Powered = true;
                }

                if(value == 6397) {
                    Face = "ceiling";
Facing = "east";
Powered = false;
                }

            }
        }

        public string Face { get; set; } = "wall";
        public string Facing { get; set; } = "north";
        public bool Powered { get; set; } = false;

        public BlockSpruceButton() {
            State = DefaultState;
        }

        public BlockSpruceButton(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }

        public BlockSpruceButton(string face, string facing, bool powered) {
            Face = face;
            Facing = facing;
            Powered = powered;
        }
    }
}