// FILE AUTOGENERATED. DO NOT MODIFY
using System;

namespace nylium.Core.Block.Blocks {

    public class BlockInfestedStone : BlockBase {

        public override string Id { get { return "minecraft:infested_stone"; } }

        public override ushort MinimumState { get { return 4499; } }
        public override ushort MaximumState { get { return 4499; } }
        public override ushort DefaultState { get { return 4499; } }

        public override ushort State {
            get {
                return DefaultState;
            }

            set {
            }
        }


        public BlockInfestedStone() {
            State = DefaultState;
        }

        public BlockInfestedStone(ushort state) {
            if(state < MinimumState || state > MaximumState) {
                throw new ArgumentOutOfRangeException("state");
            }

            State = state;
        }
    }
}