// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class NetherGoldOreBlock : BaseBlock {

        public NetherGoldOreBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 34, 72) { }
    }
}
