// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class OakLogBlock : BaseBlock {

        public Axis Axis { get; }

        public OakLogBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 35, 74) { }

        public OakLogBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 35, state) {
            if(state == 73) {
                Axis = Axis.X;
            } else if(state == 74) {
                Axis = Axis.Y;
            } else if(state == 75) {
                Axis = Axis.Z;
            }
        }

        public OakLogBlock(Chunk chunk, int x, int y, int z, Axis axis) : base(chunk, x, y, z, 35, 74) {
if(axis == Axis.X) {
                State = 73;
            } else if(axis == Axis.Y) {
                State = 74;
            } else if(axis == Axis.Z) {
                State = 75;
            }
        }
    }
}
