// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class OrangeTulipBlock : BaseBlock {

        public OrangeTulipBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 125, 1418) { }
    }
}
