// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PinkStainedGlassBlock : BaseBlock {

        public PinkStainedGlassBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 212, 4101) { }
    }
}
