// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PistonHeadBlock : BaseBlock {

        public Face Facing { get; }
        public bool _Short { get; }
        public BlockType Type { get; }

        public PistonHeadBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 101, 1362) { }

        public PistonHeadBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 101, state) {if(state == 1360) {
                Facing = Face.North;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1361) {
                Facing = Face.North;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1362) {
                Facing = Face.North;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1363) {
                Facing = Face.North;
                _Short = false;
                Type = BlockType.Sticky;
            } else if(state == 1364) {
                Facing = Face.East;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1365) {
                Facing = Face.East;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1366) {
                Facing = Face.East;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1367) {
                Facing = Face.East;
                _Short = false;
                Type = BlockType.Sticky;
            } else if(state == 1368) {
                Facing = Face.South;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1369) {
                Facing = Face.South;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1370) {
                Facing = Face.South;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1371) {
                Facing = Face.South;
                _Short = false;
                Type = BlockType.Sticky;
            } else if(state == 1372) {
                Facing = Face.West;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1373) {
                Facing = Face.West;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1374) {
                Facing = Face.West;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1375) {
                Facing = Face.West;
                _Short = false;
                Type = BlockType.Sticky;
            } else if(state == 1376) {
                Facing = Face.Up;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1377) {
                Facing = Face.Up;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1378) {
                Facing = Face.Up;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1379) {
                Facing = Face.Up;
                _Short = false;
                Type = BlockType.Sticky;
            } else if(state == 1380) {
                Facing = Face.Down;
                _Short = true;
                Type = BlockType.Normal;
            } else if(state == 1381) {
                Facing = Face.Down;
                _Short = true;
                Type = BlockType.Sticky;
            } else if(state == 1382) {
                Facing = Face.Down;
                _Short = false;
                Type = BlockType.Normal;
            } else if(state == 1383) {
                Facing = Face.Down;
                _Short = false;
                Type = BlockType.Sticky;
            }
        }

        public PistonHeadBlock(Chunk chunk, int x, int y, int z, Face facing, bool _short, BlockType type) : base(chunk, x, y, z, 101, 1362) {
if(facing == Face.North && _short == true && type == BlockType.Normal) {
                State = 1360;
            } else if(facing == Face.North && _short == true && type == BlockType.Sticky) {
                State = 1361;
            } else if(facing == Face.North && _short == false && type == BlockType.Normal) {
                State = 1362;
            } else if(facing == Face.North && _short == false && type == BlockType.Sticky) {
                State = 1363;
            } else if(facing == Face.East && _short == true && type == BlockType.Normal) {
                State = 1364;
            } else if(facing == Face.East && _short == true && type == BlockType.Sticky) {
                State = 1365;
            } else if(facing == Face.East && _short == false && type == BlockType.Normal) {
                State = 1366;
            } else if(facing == Face.East && _short == false && type == BlockType.Sticky) {
                State = 1367;
            } else if(facing == Face.South && _short == true && type == BlockType.Normal) {
                State = 1368;
            } else if(facing == Face.South && _short == true && type == BlockType.Sticky) {
                State = 1369;
            } else if(facing == Face.South && _short == false && type == BlockType.Normal) {
                State = 1370;
            } else if(facing == Face.South && _short == false && type == BlockType.Sticky) {
                State = 1371;
            } else if(facing == Face.West && _short == true && type == BlockType.Normal) {
                State = 1372;
            } else if(facing == Face.West && _short == true && type == BlockType.Sticky) {
                State = 1373;
            } else if(facing == Face.West && _short == false && type == BlockType.Normal) {
                State = 1374;
            } else if(facing == Face.West && _short == false && type == BlockType.Sticky) {
                State = 1375;
            } else if(facing == Face.Up && _short == true && type == BlockType.Normal) {
                State = 1376;
            } else if(facing == Face.Up && _short == true && type == BlockType.Sticky) {
                State = 1377;
            } else if(facing == Face.Up && _short == false && type == BlockType.Normal) {
                State = 1378;
            } else if(facing == Face.Up && _short == false && type == BlockType.Sticky) {
                State = 1379;
            } else if(facing == Face.Down && _short == true && type == BlockType.Normal) {
                State = 1380;
            } else if(facing == Face.Down && _short == true && type == BlockType.Sticky) {
                State = 1381;
            } else if(facing == Face.Down && _short == false && type == BlockType.Normal) {
                State = 1382;
            } else if(facing == Face.Down && _short == false && type == BlockType.Sticky) {
                State = 1383;
            }
        }

        public enum BlockType {

            Normal,
            Sticky
        }
    }
}
