// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PolishedDioriteSlabBlock : BaseBlock {

        public BlockType Type { get; }
        public bool Waterlogged { get; }

        public PolishedDioriteSlabBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 644, 10814) { }

        public PolishedDioriteSlabBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 644, state) {if(state == 10811) {
                Type = BlockType.Top;
                Waterlogged = true;
            } else if(state == 10812) {
                Type = BlockType.Top;
                Waterlogged = false;
            } else if(state == 10813) {
                Type = BlockType.Bottom;
                Waterlogged = true;
            } else if(state == 10814) {
                Type = BlockType.Bottom;
                Waterlogged = false;
            } else if(state == 10815) {
                Type = BlockType.Double;
                Waterlogged = true;
            } else if(state == 10816) {
                Type = BlockType.Double;
                Waterlogged = false;
            }
        }

        public PolishedDioriteSlabBlock(Chunk chunk, int x, int y, int z, BlockType type, bool waterlogged) : base(chunk, x, y, z, 644, 10814) {
if(type == BlockType.Top && waterlogged == true) {
                State = 10811;
            } else if(type == BlockType.Top && waterlogged == false) {
                State = 10812;
            } else if(type == BlockType.Bottom && waterlogged == true) {
                State = 10813;
            } else if(type == BlockType.Bottom && waterlogged == false) {
                State = 10814;
            } else if(type == BlockType.Double && waterlogged == true) {
                State = 10815;
            } else if(type == BlockType.Double && waterlogged == false) {
                State = 10816;
            }
        }

        public enum BlockType {
            
            Top,
            Bottom,
            Double
        }
    }
}
