// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PolishedBasaltBlock : BaseBlock {

        public Axis Axis { get; }

        public PolishedBasaltBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 197, 4006) { }

        public PolishedBasaltBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 197, state) {
            if(state == 4005) {
                Axis = Axis.X;
            } else if(state == 4006) {
                Axis = Axis.Y;
            } else if(state == 4007) {
                Axis = Axis.Z;
            }
        }

        public PolishedBasaltBlock(Chunk chunk, int x, int y, int z, Axis axis) : base(chunk, x, y, z, 197, 4006) {
if(axis == Axis.X) {
                State = 4005;
            } else if(axis == Axis.Y) {
                State = 4006;
            } else if(axis == Axis.Z) {
                State = 4007;
            }
        }
    }
}
