// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PurpleShulkerBoxBlock : BaseBlock {

        public Face Facing { get; }

        public PurpleShulkerBoxBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 520, 9346) { }

        public PurpleShulkerBoxBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 520, state) {
            if(state == 9342) {
                Facing = Face.North;
            } else if(state == 9343) {
                Facing = Face.East;
            } else if(state == 9344) {
                Facing = Face.South;
            } else if(state == 9345) {
                Facing = Face.West;
            } else if(state == 9346) {
                Facing = Face.Up;
            } else if(state == 9347) {
                Facing = Face.Down;
            }
        }

        public PurpleShulkerBoxBlock(Chunk chunk, int x, int y, int z, Face facing) : base(chunk, x, y, z, 520, 9346) {
if(facing == Face.North) {
                State = 9342;
            } else if(facing == Face.East) {
                State = 9343;
            } else if(facing == Face.South) {
                State = 9344;
            } else if(facing == Face.West) {
                State = 9345;
            } else if(facing == Face.Up) {
                State = 9346;
            } else if(facing == Face.Down) {
                State = 9347;
            }
        }
    }
}
