// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class RedConcretePowderBlock : BaseBlock {

        public RedConcretePowderBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 572, 9472) { }
    }
}
