// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class StrippedCrimsonStemBlock : BaseBlock {

        public Axis Axis { get; }

        public StrippedCrimsonStemBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 693, 14987) { }

        public StrippedCrimsonStemBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z, 693, state) {
            if(state == 14986) {
                Axis = Axis.X;
            } else if(state == 14987) {
                Axis = Axis.Y;
            } else if(state == 14988) {
                Axis = Axis.Z;
            }
        }

        public StrippedCrimsonStemBlock(Chunk chunk, int x, int y, int z, Axis axis) : base(chunk, x, y, z, 693, 14987) {
if(axis == Axis.X) {
                State = 14986;
            } else if(axis == Axis.Y) {
                State = 14987;
            } else if(axis == Axis.Z) {
                State = 14988;
            }
        }
    }
}
