// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class WhiteTerracottaBlock : BaseBlock {

        public WhiteTerracottaBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 343, 6851) { }
    }
}
