// FILE AUTOGENERATED. DO NOT MODIFY
namespace Starfield.Core.Item.Items {

    [Item("minecraft:prismarine_brick_stairs", 415, 64, 384)]
    public class ItemPrismarineBrickStairs : BlockItem { }
}