// FILE AUTOGENERATED. DO NOT MODIFY
namespace Starfield.Core.Item.Items {

    [Item("minecraft:dark_prismarine_stairs", 416, 64, 385)]
    public class ItemDarkPrismarineStairs : BlockItem { }
}