// FILE AUTOGENERATED. DO NOT MODIFY
namespace Starfield.Core.Item.Items {

    [Item("minecraft:yellow_stained_glass_pane", 399, 64, 363)]
    public class ItemYellowStainedGlassPane : BlockItem { }
}