// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class Air : BaseBlock {

        public Air(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 0, 0) { }
    }
}
