// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BambooSapling : BaseBlock {

        public BambooSapling(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 621, 9655) { }
    }
}
