// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BeeNestBlock : BaseBlock {

        public Face Facing { get; }
        public int Honey_Level { get; }

        public BeeNestBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 730, 15784) { }

        public BeeNestBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 730, state) {
            if(state == 15784) {
                Facing = Face.North;
                Honey_Level = 0;
            } else if(state == 15785) {
                Facing = Face.North;
                Honey_Level = 1;
            } else if(state == 15786) {
                Facing = Face.North;
                Honey_Level = 2;
            } else if(state == 15787) {
                Facing = Face.North;
                Honey_Level = 3;
            } else if(state == 15788) {
                Facing = Face.North;
                Honey_Level = 4;
            } else if(state == 15789) {
                Facing = Face.North;
                Honey_Level = 5;
            } else if(state == 15790) {
                Facing = Face.South;
                Honey_Level = 0;
            } else if(state == 15791) {
                Facing = Face.South;
                Honey_Level = 1;
            } else if(state == 15792) {
                Facing = Face.South;
                Honey_Level = 2;
            } else if(state == 15793) {
                Facing = Face.South;
                Honey_Level = 3;
            } else if(state == 15794) {
                Facing = Face.South;
                Honey_Level = 4;
            } else if(state == 15795) {
                Facing = Face.South;
                Honey_Level = 5;
            } else if(state == 15796) {
                Facing = Face.West;
                Honey_Level = 0;
            } else if(state == 15797) {
                Facing = Face.West;
                Honey_Level = 1;
            } else if(state == 15798) {
                Facing = Face.West;
                Honey_Level = 2;
            } else if(state == 15799) {
                Facing = Face.West;
                Honey_Level = 3;
            } else if(state == 15800) {
                Facing = Face.West;
                Honey_Level = 4;
            } else if(state == 15801) {
                Facing = Face.West;
                Honey_Level = 5;
            } else if(state == 15802) {
                Facing = Face.East;
                Honey_Level = 0;
            } else if(state == 15803) {
                Facing = Face.East;
                Honey_Level = 1;
            } else if(state == 15804) {
                Facing = Face.East;
                Honey_Level = 2;
            } else if(state == 15805) {
                Facing = Face.East;
                Honey_Level = 3;
            } else if(state == 15806) {
                Facing = Face.East;
                Honey_Level = 4;
            } else if(state == 15807) {
                Facing = Face.East;
                Honey_Level = 5;
            }
        }

        public BeeNestBlock(Chunk chunk, int x, int y, int z, Face facing, int honey_level) : base(chunk, x, y, z, 730, 15784) {
if(facing == Face.North && honey_level == 0) {
                State = 15784;
            } else if(facing == Face.North && honey_level == 1) {
                State = 15785;
            } else if(facing == Face.North && honey_level == 2) {
                State = 15786;
            } else if(facing == Face.North && honey_level == 3) {
                State = 15787;
            } else if(facing == Face.North && honey_level == 4) {
                State = 15788;
            } else if(facing == Face.North && honey_level == 5) {
                State = 15789;
            } else if(facing == Face.South && honey_level == 0) {
                State = 15790;
            } else if(facing == Face.South && honey_level == 1) {
                State = 15791;
            } else if(facing == Face.South && honey_level == 2) {
                State = 15792;
            } else if(facing == Face.South && honey_level == 3) {
                State = 15793;
            } else if(facing == Face.South && honey_level == 4) {
                State = 15794;
            } else if(facing == Face.South && honey_level == 5) {
                State = 15795;
            } else if(facing == Face.West && honey_level == 0) {
                State = 15796;
            } else if(facing == Face.West && honey_level == 1) {
                State = 15797;
            } else if(facing == Face.West && honey_level == 2) {
                State = 15798;
            } else if(facing == Face.West && honey_level == 3) {
                State = 15799;
            } else if(facing == Face.West && honey_level == 4) {
                State = 15800;
            } else if(facing == Face.West && honey_level == 5) {
                State = 15801;
            } else if(facing == Face.East && honey_level == 0) {
                State = 15802;
            } else if(facing == Face.East && honey_level == 1) {
                State = 15803;
            } else if(facing == Face.East && honey_level == 2) {
                State = 15804;
            } else if(facing == Face.East && honey_level == 3) {
                State = 15805;
            } else if(facing == Face.East && honey_level == 4) {
                State = 15806;
            } else if(facing == Face.East && honey_level == 5) {
                State = 15807;
            }
        }
    }
}
