// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BlackCarpet : BaseBlock {

        public BlackCarpet(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 406, 7885) { }
    }
}
