// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BlueBedBlock : BaseBlock {

        public Face Facing { get; }
        public bool Occupied { get; }
        public Part Part { get; }

        public BlueBedBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 86, 1228) { }

        public BlueBedBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 86, state) {
            if(state == 1225) {
                Facing = Face.North;
                Occupied = true;
                Part = Part.Head;
            } else if(state == 1226) {
                Facing = Face.North;
                Occupied = true;
                Part = Part.Foot;
            } else if(state == 1227) {
                Facing = Face.North;
                Occupied = false;
                Part = Part.Head;
            } else if(state == 1228) {
                Facing = Face.North;
                Occupied = false;
                Part = Part.Foot;
            } else if(state == 1229) {
                Facing = Face.South;
                Occupied = true;
                Part = Part.Head;
            } else if(state == 1230) {
                Facing = Face.South;
                Occupied = true;
                Part = Part.Foot;
            } else if(state == 1231) {
                Facing = Face.South;
                Occupied = false;
                Part = Part.Head;
            } else if(state == 1232) {
                Facing = Face.South;
                Occupied = false;
                Part = Part.Foot;
            } else if(state == 1233) {
                Facing = Face.West;
                Occupied = true;
                Part = Part.Head;
            } else if(state == 1234) {
                Facing = Face.West;
                Occupied = true;
                Part = Part.Foot;
            } else if(state == 1235) {
                Facing = Face.West;
                Occupied = false;
                Part = Part.Head;
            } else if(state == 1236) {
                Facing = Face.West;
                Occupied = false;
                Part = Part.Foot;
            } else if(state == 1237) {
                Facing = Face.East;
                Occupied = true;
                Part = Part.Head;
            } else if(state == 1238) {
                Facing = Face.East;
                Occupied = true;
                Part = Part.Foot;
            } else if(state == 1239) {
                Facing = Face.East;
                Occupied = false;
                Part = Part.Head;
            } else if(state == 1240) {
                Facing = Face.East;
                Occupied = false;
                Part = Part.Foot;
            }
        }

        public BlueBedBlock(Chunk chunk, int x, int y, int z, Face facing, bool occupied, Part part) : base(chunk, x, y, z, 86, 1228) {
if(facing == Face.North && occupied == true && part == Part.Head) {
                State = 1225;
            } else if(facing == Face.North && occupied == true && part == Part.Foot) {
                State = 1226;
            } else if(facing == Face.North && occupied == false && part == Part.Head) {
                State = 1227;
            } else if(facing == Face.North && occupied == false && part == Part.Foot) {
                State = 1228;
            } else if(facing == Face.South && occupied == true && part == Part.Head) {
                State = 1229;
            } else if(facing == Face.South && occupied == true && part == Part.Foot) {
                State = 1230;
            } else if(facing == Face.South && occupied == false && part == Part.Head) {
                State = 1231;
            } else if(facing == Face.South && occupied == false && part == Part.Foot) {
                State = 1232;
            } else if(facing == Face.West && occupied == true && part == Part.Head) {
                State = 1233;
            } else if(facing == Face.West && occupied == true && part == Part.Foot) {
                State = 1234;
            } else if(facing == Face.West && occupied == false && part == Part.Head) {
                State = 1235;
            } else if(facing == Face.West && occupied == false && part == Part.Foot) {
                State = 1236;
            } else if(facing == Face.East && occupied == true && part == Part.Head) {
                State = 1237;
            } else if(facing == Face.East && occupied == true && part == Part.Foot) {
                State = 1238;
            } else if(facing == Face.East && occupied == false && part == Part.Head) {
                State = 1239;
            } else if(facing == Face.East && occupied == false && part == Part.Foot) {
                State = 1240;
            }
        }
    }
}
