// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BlueIce : BaseBlock {

        public BlueIce(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 619, 9652) { }
    }
}
