// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BlueCarpet : BaseBlock {

        public BlueCarpet(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 402, 7881) { }
    }
}
