// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BrainCoralFanBlock : BaseBlock {

        public bool Waterlogged { get; }

        public BrainCoralFanBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 604, 9556) { }

        public BrainCoralFanBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 604, state) {
            if(state == 9556) {
                Waterlogged = true;
            } else if(state == 9557) {
                Waterlogged = false;
            }
        }

        public BrainCoralFanBlock(Chunk chunk, int x, int y, int z, bool waterlogged) : base(chunk, x, y, z, 604, 9556) {
if(waterlogged == true) {
                State = 9556;
            } else if(waterlogged == false) {
                State = 9557;
            }
        }
    }
}
