// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class BrownTerracotta : BaseBlock {

        public BrownTerracotta(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 355, 6863) { }
    }
}
