// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class CartographyTableBlock : BaseBlock {

        public CartographyTableBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 671, 14823) { }
    }
}
