// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class CyanTerracotta : BaseBlock {

        public CyanTerracotta(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 352, 6860) { }
    }
}
