// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class CyanBannerBlock : BaseBlock {

        public int Rotation { get; }

        public CyanBannerBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 425, 8045) { }

        public CyanBannerBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 425, state) {
            if(state == 8045) {
                Rotation = 0;
            } else if(state == 8046) {
                Rotation = 1;
            } else if(state == 8047) {
                Rotation = 2;
            } else if(state == 8048) {
                Rotation = 3;
            } else if(state == 8049) {
                Rotation = 4;
            } else if(state == 8050) {
                Rotation = 5;
            } else if(state == 8051) {
                Rotation = 6;
            } else if(state == 8052) {
                Rotation = 7;
            } else if(state == 8053) {
                Rotation = 8;
            } else if(state == 8054) {
                Rotation = 9;
            } else if(state == 8055) {
                Rotation = 10;
            } else if(state == 8056) {
                Rotation = 11;
            } else if(state == 8057) {
                Rotation = 12;
            } else if(state == 8058) {
                Rotation = 13;
            } else if(state == 8059) {
                Rotation = 14;
            } else if(state == 8060) {
                Rotation = 15;
            }
        }

        public CyanBannerBlock(Chunk chunk, int x, int y, int z, int rotation) : base(chunk, x, y, z, 425, 8045) {
if(rotation == 0) {
                State = 8045;
            } else if(rotation == 1) {
                State = 8046;
            } else if(rotation == 2) {
                State = 8047;
            } else if(rotation == 3) {
                State = 8048;
            } else if(rotation == 4) {
                State = 8049;
            } else if(rotation == 5) {
                State = 8050;
            } else if(rotation == 6) {
                State = 8051;
            } else if(rotation == 7) {
                State = 8052;
            } else if(rotation == 8) {
                State = 8053;
            } else if(rotation == 9) {
                State = 8054;
            } else if(rotation == 10) {
                State = 8055;
            } else if(rotation == 11) {
                State = 8056;
            } else if(rotation == 12) {
                State = 8057;
            } else if(rotation == 13) {
                State = 8058;
            } else if(rotation == 14) {
                State = 8059;
            } else if(rotation == 15) {
                State = 8060;
            }
        }
    }
}
