// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class DarkOakSlabBlock : BaseBlock {

        public Type Type { get; }
        public bool Waterlogged { get; }

        public DarkOakSlabBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 457, 8337) { }

        public DarkOakSlabBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 457, state) {if(state == 8334) {
                Type = Type.Top;
                Waterlogged = true;
            } else if(state == 8335) {
                Type = Type.Top;
                Waterlogged = false;
            } else if(state == 8336) {
                Type = Type.Bottom;
                Waterlogged = true;
            } else if(state == 8337) {
                Type = Type.Bottom;
                Waterlogged = false;
            } else if(state == 8338) {
                Type = Type.Double;
                Waterlogged = true;
            } else if(state == 8339) {
                Type = Type.Double;
                Waterlogged = false;
            }
        }

        public DarkOakSlabBlock(Chunk chunk, int x, int y, int z, Type type, bool waterlogged) : base(chunk, x, y, z, 457, 8337) {
if(type == Type.Top && waterlogged == true) {
                State = 8334;
            } else if(type == Type.Top && waterlogged == false) {
                State = 8335;
            } else if(type == Type.Bottom && waterlogged == true) {
                State = 8336;
            } else if(type == Type.Bottom && waterlogged == false) {
                State = 8337;
            } else if(type == Type.Double && waterlogged == true) {
                State = 8338;
            } else if(type == Type.Double && waterlogged == false) {
                State = 8339;
            }
        }

        public enum Type {
            
            Top,
            Bottom,
            Double
        }
    }
}
