// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class DarkOakFenceBlock : BaseBlock {

        public bool East { get; }
        public bool North { get; }
        public bool South { get; }
        public bool Waterlogged { get; }
        public bool West { get; }

        public DarkOakFenceBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 484, 8741) { }

        public DarkOakFenceBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 484, state) {
            if(state == 8710) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 8711) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 8712) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 8713) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 8714) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 8715) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 8716) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 8717) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 8718) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 8719) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 8720) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 8721) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 8722) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 8723) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 8724) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 8725) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 8726) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 8727) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 8728) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 8729) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 8730) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 8731) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 8732) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 8733) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 8734) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 8735) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 8736) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 8737) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 8738) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 8739) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 8740) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 8741) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            }
        }

        public DarkOakFenceBlock(Chunk chunk, int x, int y, int z, bool east, bool north, bool south, bool waterlogged, bool west) : base(chunk, x, y, z, 484, 8741) {
if(east == true && north == true && south == true && waterlogged == true && west == true) {
                State = 8710;
            } else if(east == true && north == true && south == true && waterlogged == true && west == false) {
                State = 8711;
            } else if(east == true && north == true && south == true && waterlogged == false && west == true) {
                State = 8712;
            } else if(east == true && north == true && south == true && waterlogged == false && west == false) {
                State = 8713;
            } else if(east == true && north == true && south == false && waterlogged == true && west == true) {
                State = 8714;
            } else if(east == true && north == true && south == false && waterlogged == true && west == false) {
                State = 8715;
            } else if(east == true && north == true && south == false && waterlogged == false && west == true) {
                State = 8716;
            } else if(east == true && north == true && south == false && waterlogged == false && west == false) {
                State = 8717;
            } else if(east == true && north == false && south == true && waterlogged == true && west == true) {
                State = 8718;
            } else if(east == true && north == false && south == true && waterlogged == true && west == false) {
                State = 8719;
            } else if(east == true && north == false && south == true && waterlogged == false && west == true) {
                State = 8720;
            } else if(east == true && north == false && south == true && waterlogged == false && west == false) {
                State = 8721;
            } else if(east == true && north == false && south == false && waterlogged == true && west == true) {
                State = 8722;
            } else if(east == true && north == false && south == false && waterlogged == true && west == false) {
                State = 8723;
            } else if(east == true && north == false && south == false && waterlogged == false && west == true) {
                State = 8724;
            } else if(east == true && north == false && south == false && waterlogged == false && west == false) {
                State = 8725;
            } else if(east == false && north == true && south == true && waterlogged == true && west == true) {
                State = 8726;
            } else if(east == false && north == true && south == true && waterlogged == true && west == false) {
                State = 8727;
            } else if(east == false && north == true && south == true && waterlogged == false && west == true) {
                State = 8728;
            } else if(east == false && north == true && south == true && waterlogged == false && west == false) {
                State = 8729;
            } else if(east == false && north == true && south == false && waterlogged == true && west == true) {
                State = 8730;
            } else if(east == false && north == true && south == false && waterlogged == true && west == false) {
                State = 8731;
            } else if(east == false && north == true && south == false && waterlogged == false && west == true) {
                State = 8732;
            } else if(east == false && north == true && south == false && waterlogged == false && west == false) {
                State = 8733;
            } else if(east == false && north == false && south == true && waterlogged == true && west == true) {
                State = 8734;
            } else if(east == false && north == false && south == true && waterlogged == true && west == false) {
                State = 8735;
            } else if(east == false && north == false && south == true && waterlogged == false && west == true) {
                State = 8736;
            } else if(east == false && north == false && south == true && waterlogged == false && west == false) {
                State = 8737;
            } else if(east == false && north == false && south == false && waterlogged == true && west == true) {
                State = 8738;
            } else if(east == false && north == false && south == false && waterlogged == true && west == false) {
                State = 8739;
            } else if(east == false && north == false && south == false && waterlogged == false && west == true) {
                State = 8740;
            } else if(east == false && north == false && south == false && waterlogged == false && west == false) {
                State = 8741;
            }
        }
    }
}
