// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class GrassPath : BaseBlock {

        public GrassPath(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 498, 9227) { }
    }
}
