// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class InfestedCobblestone : BaseBlock {

        public InfestedCobblestone(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 233, 4500) { }
    }
}
