// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class LightBlueStainedGlass : BaseBlock {

        public LightBlueStainedGlass(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 209, 4098) { }
    }
}
