// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class LightBlueConcretePowder : BaseBlock {

        public LightBlueConcretePowder(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 561, 9461) { }
    }
}
