// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class LilacBlock : BaseBlock {

        public Half Half { get; }

        public LilacBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 411, 7892) { }

        public LilacBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 411, state) {
            if(state == 7891) {
                Half = Half.Upper;
            } else if(state == 7892) {
                Half = Half.Lower;
            }
        }

        public LilacBlock(Chunk chunk, int x, int y, int z, Half half) : base(chunk, x, y, z, 411, 7892) {
if(half == Half.Upper) {
                State = 7891;
            } else if(half == Half.Lower) {
                State = 7892;
            }
        }
    }
}
