// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class MossyStoneBricksBlock : BaseBlock {

        public MossyStoneBricksBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 229, 4496) { }
    }
}
