// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class OakFenceBlock : BaseBlock {

        public bool East { get; }
        public bool North { get; }
        public bool South { get; }
        public bool Waterlogged { get; }
        public bool West { get; }

        public OakFenceBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 191, 3997) { }

        public OakFenceBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 191, state) {
            if(state == 3966) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 3967) {
                East = true;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 3968) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 3969) {
                East = true;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 3970) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 3971) {
                East = true;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 3972) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 3973) {
                East = true;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 3974) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 3975) {
                East = true;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 3976) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 3977) {
                East = true;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 3978) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 3979) {
                East = true;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 3980) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 3981) {
                East = true;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 3982) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 3983) {
                East = false;
                North = true;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 3984) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 3985) {
                East = false;
                North = true;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 3986) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 3987) {
                East = false;
                North = true;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 3988) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 3989) {
                East = false;
                North = true;
                South = false;
                Waterlogged = false;
                West = false;
            } else if(state == 3990) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = true;
            } else if(state == 3991) {
                East = false;
                North = false;
                South = true;
                Waterlogged = true;
                West = false;
            } else if(state == 3992) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = true;
            } else if(state == 3993) {
                East = false;
                North = false;
                South = true;
                Waterlogged = false;
                West = false;
            } else if(state == 3994) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = true;
            } else if(state == 3995) {
                East = false;
                North = false;
                South = false;
                Waterlogged = true;
                West = false;
            } else if(state == 3996) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = true;
            } else if(state == 3997) {
                East = false;
                North = false;
                South = false;
                Waterlogged = false;
                West = false;
            }
        }

        public OakFenceBlock(Chunk chunk, int x, int y, int z, bool east, bool north, bool south, bool waterlogged, bool west) : base(chunk, x, y, z, 191, 3997) {
if(east == true && north == true && south == true && waterlogged == true && west == true) {
                State = 3966;
            } else if(east == true && north == true && south == true && waterlogged == true && west == false) {
                State = 3967;
            } else if(east == true && north == true && south == true && waterlogged == false && west == true) {
                State = 3968;
            } else if(east == true && north == true && south == true && waterlogged == false && west == false) {
                State = 3969;
            } else if(east == true && north == true && south == false && waterlogged == true && west == true) {
                State = 3970;
            } else if(east == true && north == true && south == false && waterlogged == true && west == false) {
                State = 3971;
            } else if(east == true && north == true && south == false && waterlogged == false && west == true) {
                State = 3972;
            } else if(east == true && north == true && south == false && waterlogged == false && west == false) {
                State = 3973;
            } else if(east == true && north == false && south == true && waterlogged == true && west == true) {
                State = 3974;
            } else if(east == true && north == false && south == true && waterlogged == true && west == false) {
                State = 3975;
            } else if(east == true && north == false && south == true && waterlogged == false && west == true) {
                State = 3976;
            } else if(east == true && north == false && south == true && waterlogged == false && west == false) {
                State = 3977;
            } else if(east == true && north == false && south == false && waterlogged == true && west == true) {
                State = 3978;
            } else if(east == true && north == false && south == false && waterlogged == true && west == false) {
                State = 3979;
            } else if(east == true && north == false && south == false && waterlogged == false && west == true) {
                State = 3980;
            } else if(east == true && north == false && south == false && waterlogged == false && west == false) {
                State = 3981;
            } else if(east == false && north == true && south == true && waterlogged == true && west == true) {
                State = 3982;
            } else if(east == false && north == true && south == true && waterlogged == true && west == false) {
                State = 3983;
            } else if(east == false && north == true && south == true && waterlogged == false && west == true) {
                State = 3984;
            } else if(east == false && north == true && south == true && waterlogged == false && west == false) {
                State = 3985;
            } else if(east == false && north == true && south == false && waterlogged == true && west == true) {
                State = 3986;
            } else if(east == false && north == true && south == false && waterlogged == true && west == false) {
                State = 3987;
            } else if(east == false && north == true && south == false && waterlogged == false && west == true) {
                State = 3988;
            } else if(east == false && north == true && south == false && waterlogged == false && west == false) {
                State = 3989;
            } else if(east == false && north == false && south == true && waterlogged == true && west == true) {
                State = 3990;
            } else if(east == false && north == false && south == true && waterlogged == true && west == false) {
                State = 3991;
            } else if(east == false && north == false && south == true && waterlogged == false && west == true) {
                State = 3992;
            } else if(east == false && north == false && south == true && waterlogged == false && west == false) {
                State = 3993;
            } else if(east == false && north == false && south == false && waterlogged == true && west == true) {
                State = 3994;
            } else if(east == false && north == false && south == false && waterlogged == true && west == false) {
                State = 3995;
            } else if(east == false && north == false && south == false && waterlogged == false && west == true) {
                State = 3996;
            } else if(east == false && north == false && south == false && waterlogged == false && west == false) {
                State = 3997;
            }
        }
    }
}
