// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class OakPressurePlateBlock : BaseBlock {

        public bool Powered { get; }

        public OakPressurePlateBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 174, 3874) { }

        public OakPressurePlateBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 174, state) {
            if(state == 3873) {
                Powered = true;
            } else if(state == 3874) {
                Powered = false;
            }
        }

        public OakPressurePlateBlock(Chunk chunk, int x, int y, int z, bool powered) : base(chunk, x, y, z, 174, 3874) {
if(powered == true) {
                State = 3873;
            } else if(powered == false) {
                State = 3874;
            }
        }
    }
}
