// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PoppyBlock : BaseBlock {

        public PoppyBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 120, 1413) { }
    }
}
