// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PottedPoppy : BaseBlock {

        public PottedPoppy(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 290, 6318) { }
    }
}
