// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PumpkinStemBlock : BaseBlock {

        public int Age { get; }

        public PumpkinStemBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 247, 4776) { }

        public PumpkinStemBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 247, state) {
            if(state == 4776) {
                Age = 0;
            } else if(state == 4777) {
                Age = 1;
            } else if(state == 4778) {
                Age = 2;
            } else if(state == 4779) {
                Age = 3;
            } else if(state == 4780) {
                Age = 4;
            } else if(state == 4781) {
                Age = 5;
            } else if(state == 4782) {
                Age = 6;
            } else if(state == 4783) {
                Age = 7;
            }
        }

        public PumpkinStemBlock(Chunk chunk, int x, int y, int z, int age) : base(chunk, x, y, z, 247, 4776) {
if(age == 0) {
                State = 4776;
            } else if(age == 1) {
                State = 4777;
            } else if(age == 2) {
                State = 4778;
            } else if(age == 3) {
                State = 4779;
            } else if(age == 4) {
                State = 4780;
            } else if(age == 5) {
                State = 4781;
            } else if(age == 6) {
                State = 4782;
            } else if(age == 7) {
                State = 4783;
            }
        }
    }
}
