// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class PurpleCarpet : BaseBlock {

        public PurpleCarpet(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 401, 7880) { }
    }
}
