// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class QuartzBricks : BaseBlock {

        public QuartzBricks(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 762, 17111) { }
    }
}
