// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class SlimeBlock : BaseBlock {

        public SlimeBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 377, 7539) { }
    }
}
