// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class SoulSand : BaseBlock {

        public SoulSand(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 194, 4000) { }
    }
}
