// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class SoulSoil : BaseBlock {

        public SoulSoil(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 195, 4001) { }
    }
}
