// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class SpruceFenceGateBlock : BaseBlock {

        public Face Facing { get; }
        public bool In_Wall { get; }
        public bool Open { get; }
        public bool Powered { get; }

        public SpruceFenceGateBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 475, 8429) { }

        public SpruceFenceGateBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 475, state) {
            if(state == 8422) {
                Facing = Face.North;
                In_Wall = true;
                Open = true;
                Powered = true;
            } else if(state == 8423) {
                Facing = Face.North;
                In_Wall = true;
                Open = true;
                Powered = false;
            } else if(state == 8424) {
                Facing = Face.North;
                In_Wall = true;
                Open = false;
                Powered = true;
            } else if(state == 8425) {
                Facing = Face.North;
                In_Wall = true;
                Open = false;
                Powered = false;
            } else if(state == 8426) {
                Facing = Face.North;
                In_Wall = false;
                Open = true;
                Powered = true;
            } else if(state == 8427) {
                Facing = Face.North;
                In_Wall = false;
                Open = true;
                Powered = false;
            } else if(state == 8428) {
                Facing = Face.North;
                In_Wall = false;
                Open = false;
                Powered = true;
            } else if(state == 8429) {
                Facing = Face.North;
                In_Wall = false;
                Open = false;
                Powered = false;
            } else if(state == 8430) {
                Facing = Face.South;
                In_Wall = true;
                Open = true;
                Powered = true;
            } else if(state == 8431) {
                Facing = Face.South;
                In_Wall = true;
                Open = true;
                Powered = false;
            } else if(state == 8432) {
                Facing = Face.South;
                In_Wall = true;
                Open = false;
                Powered = true;
            } else if(state == 8433) {
                Facing = Face.South;
                In_Wall = true;
                Open = false;
                Powered = false;
            } else if(state == 8434) {
                Facing = Face.South;
                In_Wall = false;
                Open = true;
                Powered = true;
            } else if(state == 8435) {
                Facing = Face.South;
                In_Wall = false;
                Open = true;
                Powered = false;
            } else if(state == 8436) {
                Facing = Face.South;
                In_Wall = false;
                Open = false;
                Powered = true;
            } else if(state == 8437) {
                Facing = Face.South;
                In_Wall = false;
                Open = false;
                Powered = false;
            } else if(state == 8438) {
                Facing = Face.West;
                In_Wall = true;
                Open = true;
                Powered = true;
            } else if(state == 8439) {
                Facing = Face.West;
                In_Wall = true;
                Open = true;
                Powered = false;
            } else if(state == 8440) {
                Facing = Face.West;
                In_Wall = true;
                Open = false;
                Powered = true;
            } else if(state == 8441) {
                Facing = Face.West;
                In_Wall = true;
                Open = false;
                Powered = false;
            } else if(state == 8442) {
                Facing = Face.West;
                In_Wall = false;
                Open = true;
                Powered = true;
            } else if(state == 8443) {
                Facing = Face.West;
                In_Wall = false;
                Open = true;
                Powered = false;
            } else if(state == 8444) {
                Facing = Face.West;
                In_Wall = false;
                Open = false;
                Powered = true;
            } else if(state == 8445) {
                Facing = Face.West;
                In_Wall = false;
                Open = false;
                Powered = false;
            } else if(state == 8446) {
                Facing = Face.East;
                In_Wall = true;
                Open = true;
                Powered = true;
            } else if(state == 8447) {
                Facing = Face.East;
                In_Wall = true;
                Open = true;
                Powered = false;
            } else if(state == 8448) {
                Facing = Face.East;
                In_Wall = true;
                Open = false;
                Powered = true;
            } else if(state == 8449) {
                Facing = Face.East;
                In_Wall = true;
                Open = false;
                Powered = false;
            } else if(state == 8450) {
                Facing = Face.East;
                In_Wall = false;
                Open = true;
                Powered = true;
            } else if(state == 8451) {
                Facing = Face.East;
                In_Wall = false;
                Open = true;
                Powered = false;
            } else if(state == 8452) {
                Facing = Face.East;
                In_Wall = false;
                Open = false;
                Powered = true;
            } else if(state == 8453) {
                Facing = Face.East;
                In_Wall = false;
                Open = false;
                Powered = false;
            }
        }

        public SpruceFenceGateBlock(Chunk chunk, int x, int y, int z, Face facing, bool in_wall, bool open, bool powered) : base(chunk, x, y, z, 475, 8429) {
if(facing == Face.North && in_wall == true && open == true && powered == true) {
                State = 8422;
            } else if(facing == Face.North && in_wall == true && open == true && powered == false) {
                State = 8423;
            } else if(facing == Face.North && in_wall == true && open == false && powered == true) {
                State = 8424;
            } else if(facing == Face.North && in_wall == true && open == false && powered == false) {
                State = 8425;
            } else if(facing == Face.North && in_wall == false && open == true && powered == true) {
                State = 8426;
            } else if(facing == Face.North && in_wall == false && open == true && powered == false) {
                State = 8427;
            } else if(facing == Face.North && in_wall == false && open == false && powered == true) {
                State = 8428;
            } else if(facing == Face.North && in_wall == false && open == false && powered == false) {
                State = 8429;
            } else if(facing == Face.South && in_wall == true && open == true && powered == true) {
                State = 8430;
            } else if(facing == Face.South && in_wall == true && open == true && powered == false) {
                State = 8431;
            } else if(facing == Face.South && in_wall == true && open == false && powered == true) {
                State = 8432;
            } else if(facing == Face.South && in_wall == true && open == false && powered == false) {
                State = 8433;
            } else if(facing == Face.South && in_wall == false && open == true && powered == true) {
                State = 8434;
            } else if(facing == Face.South && in_wall == false && open == true && powered == false) {
                State = 8435;
            } else if(facing == Face.South && in_wall == false && open == false && powered == true) {
                State = 8436;
            } else if(facing == Face.South && in_wall == false && open == false && powered == false) {
                State = 8437;
            } else if(facing == Face.West && in_wall == true && open == true && powered == true) {
                State = 8438;
            } else if(facing == Face.West && in_wall == true && open == true && powered == false) {
                State = 8439;
            } else if(facing == Face.West && in_wall == true && open == false && powered == true) {
                State = 8440;
            } else if(facing == Face.West && in_wall == true && open == false && powered == false) {
                State = 8441;
            } else if(facing == Face.West && in_wall == false && open == true && powered == true) {
                State = 8442;
            } else if(facing == Face.West && in_wall == false && open == true && powered == false) {
                State = 8443;
            } else if(facing == Face.West && in_wall == false && open == false && powered == true) {
                State = 8444;
            } else if(facing == Face.West && in_wall == false && open == false && powered == false) {
                State = 8445;
            } else if(facing == Face.East && in_wall == true && open == true && powered == true) {
                State = 8446;
            } else if(facing == Face.East && in_wall == true && open == true && powered == false) {
                State = 8447;
            } else if(facing == Face.East && in_wall == true && open == false && powered == true) {
                State = 8448;
            } else if(facing == Face.East && in_wall == true && open == false && powered == false) {
                State = 8449;
            } else if(facing == Face.East && in_wall == false && open == true && powered == true) {
                State = 8450;
            } else if(facing == Face.East && in_wall == false && open == true && powered == false) {
                State = 8451;
            } else if(facing == Face.East && in_wall == false && open == false && powered == true) {
                State = 8452;
            } else if(facing == Face.East && in_wall == false && open == false && powered == false) {
                State = 8453;
            }
        }
    }
}
