// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class StoneBrickSlabBlock : BaseBlock {

        public Type Type { get; }
        public bool Waterlogged { get; }

        public StoneBrickSlabBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 465, 8385) { }

        public StoneBrickSlabBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 465, state) {if(state == 8382) {
                Type = Type.Top;
                Waterlogged = true;
            } else if(state == 8383) {
                Type = Type.Top;
                Waterlogged = false;
            } else if(state == 8384) {
                Type = Type.Bottom;
                Waterlogged = true;
            } else if(state == 8385) {
                Type = Type.Bottom;
                Waterlogged = false;
            } else if(state == 8386) {
                Type = Type.Double;
                Waterlogged = true;
            } else if(state == 8387) {
                Type = Type.Double;
                Waterlogged = false;
            }
        }

        public StoneBrickSlabBlock(Chunk chunk, int x, int y, int z, Type type, bool waterlogged) : base(chunk, x, y, z, 465, 8385) {
if(type == Type.Top && waterlogged == true) {
                State = 8382;
            } else if(type == Type.Top && waterlogged == false) {
                State = 8383;
            } else if(type == Type.Bottom && waterlogged == true) {
                State = 8384;
            } else if(type == Type.Bottom && waterlogged == false) {
                State = 8385;
            } else if(type == Type.Double && waterlogged == true) {
                State = 8386;
            } else if(type == Type.Double && waterlogged == false) {
                State = 8387;
            }
        }

        public enum Type {
            
            Top,
            Bottom,
            Double
        }
    }
}
