// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class StructureBlockBlock : BaseBlock {


        public StructureBlockBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 726, 15743) { }

        public StructureBlockBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 726, state) {
            if(state == 15743) {
                
            } else if(state == 15744) {
                
            } else if(state == 15745) {
                
            } else if(state == 15746) {
                
            }
        }

        public StructureBlockBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 726, 15743) {
if() {
                State = 15743;
            } else if() {
                State = 15744;
            } else if() {
                State = 15745;
            } else if() {
                State = 15746;
            }
        }
    }
}
