// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class TntBlock : BaseBlock {

        public bool Unstable { get; }

        public TntBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 137, 1431) { }

        public TntBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 137, state) {
            if(state == 1430) {
                Unstable = true;
            } else if(state == 1431) {
                Unstable = false;
            }
        }

        public TntBlock(Chunk chunk, int x, int y, int z, bool unstable) : base(chunk, x, y, z, 137, 1431) {
if(unstable == true) {
                State = 1430;
            } else if(unstable == false) {
                State = 1431;
            }
        }
    }
}
