// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class VineBlock : BaseBlock {

        public bool East { get; }
        public bool North { get; }
        public bool South { get; }
        public bool Up { get; }
        public bool West { get; }

        public VineBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 249, 4823) { }

        public VineBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 249, state) {
            if(state == 4792) {
                East = true;
                North = true;
                South = true;
                Up = true;
                West = true;
            } else if(state == 4793) {
                East = true;
                North = true;
                South = true;
                Up = true;
                West = false;
            } else if(state == 4794) {
                East = true;
                North = true;
                South = true;
                Up = false;
                West = true;
            } else if(state == 4795) {
                East = true;
                North = true;
                South = true;
                Up = false;
                West = false;
            } else if(state == 4796) {
                East = true;
                North = true;
                South = false;
                Up = true;
                West = true;
            } else if(state == 4797) {
                East = true;
                North = true;
                South = false;
                Up = true;
                West = false;
            } else if(state == 4798) {
                East = true;
                North = true;
                South = false;
                Up = false;
                West = true;
            } else if(state == 4799) {
                East = true;
                North = true;
                South = false;
                Up = false;
                West = false;
            } else if(state == 4800) {
                East = true;
                North = false;
                South = true;
                Up = true;
                West = true;
            } else if(state == 4801) {
                East = true;
                North = false;
                South = true;
                Up = true;
                West = false;
            } else if(state == 4802) {
                East = true;
                North = false;
                South = true;
                Up = false;
                West = true;
            } else if(state == 4803) {
                East = true;
                North = false;
                South = true;
                Up = false;
                West = false;
            } else if(state == 4804) {
                East = true;
                North = false;
                South = false;
                Up = true;
                West = true;
            } else if(state == 4805) {
                East = true;
                North = false;
                South = false;
                Up = true;
                West = false;
            } else if(state == 4806) {
                East = true;
                North = false;
                South = false;
                Up = false;
                West = true;
            } else if(state == 4807) {
                East = true;
                North = false;
                South = false;
                Up = false;
                West = false;
            } else if(state == 4808) {
                East = false;
                North = true;
                South = true;
                Up = true;
                West = true;
            } else if(state == 4809) {
                East = false;
                North = true;
                South = true;
                Up = true;
                West = false;
            } else if(state == 4810) {
                East = false;
                North = true;
                South = true;
                Up = false;
                West = true;
            } else if(state == 4811) {
                East = false;
                North = true;
                South = true;
                Up = false;
                West = false;
            } else if(state == 4812) {
                East = false;
                North = true;
                South = false;
                Up = true;
                West = true;
            } else if(state == 4813) {
                East = false;
                North = true;
                South = false;
                Up = true;
                West = false;
            } else if(state == 4814) {
                East = false;
                North = true;
                South = false;
                Up = false;
                West = true;
            } else if(state == 4815) {
                East = false;
                North = true;
                South = false;
                Up = false;
                West = false;
            } else if(state == 4816) {
                East = false;
                North = false;
                South = true;
                Up = true;
                West = true;
            } else if(state == 4817) {
                East = false;
                North = false;
                South = true;
                Up = true;
                West = false;
            } else if(state == 4818) {
                East = false;
                North = false;
                South = true;
                Up = false;
                West = true;
            } else if(state == 4819) {
                East = false;
                North = false;
                South = true;
                Up = false;
                West = false;
            } else if(state == 4820) {
                East = false;
                North = false;
                South = false;
                Up = true;
                West = true;
            } else if(state == 4821) {
                East = false;
                North = false;
                South = false;
                Up = true;
                West = false;
            } else if(state == 4822) {
                East = false;
                North = false;
                South = false;
                Up = false;
                West = true;
            } else if(state == 4823) {
                East = false;
                North = false;
                South = false;
                Up = false;
                West = false;
            }
        }

        public VineBlock(Chunk chunk, int x, int y, int z, bool east, bool north, bool south, bool up, bool west) : base(chunk, x, y, z, 249, 4823) {
if(east == true && north == true && south == true && up == true && west == true) {
                State = 4792;
            } else if(east == true && north == true && south == true && up == true && west == false) {
                State = 4793;
            } else if(east == true && north == true && south == true && up == false && west == true) {
                State = 4794;
            } else if(east == true && north == true && south == true && up == false && west == false) {
                State = 4795;
            } else if(east == true && north == true && south == false && up == true && west == true) {
                State = 4796;
            } else if(east == true && north == true && south == false && up == true && west == false) {
                State = 4797;
            } else if(east == true && north == true && south == false && up == false && west == true) {
                State = 4798;
            } else if(east == true && north == true && south == false && up == false && west == false) {
                State = 4799;
            } else if(east == true && north == false && south == true && up == true && west == true) {
                State = 4800;
            } else if(east == true && north == false && south == true && up == true && west == false) {
                State = 4801;
            } else if(east == true && north == false && south == true && up == false && west == true) {
                State = 4802;
            } else if(east == true && north == false && south == true && up == false && west == false) {
                State = 4803;
            } else if(east == true && north == false && south == false && up == true && west == true) {
                State = 4804;
            } else if(east == true && north == false && south == false && up == true && west == false) {
                State = 4805;
            } else if(east == true && north == false && south == false && up == false && west == true) {
                State = 4806;
            } else if(east == true && north == false && south == false && up == false && west == false) {
                State = 4807;
            } else if(east == false && north == true && south == true && up == true && west == true) {
                State = 4808;
            } else if(east == false && north == true && south == true && up == true && west == false) {
                State = 4809;
            } else if(east == false && north == true && south == true && up == false && west == true) {
                State = 4810;
            } else if(east == false && north == true && south == true && up == false && west == false) {
                State = 4811;
            } else if(east == false && north == true && south == false && up == true && west == true) {
                State = 4812;
            } else if(east == false && north == true && south == false && up == true && west == false) {
                State = 4813;
            } else if(east == false && north == true && south == false && up == false && west == true) {
                State = 4814;
            } else if(east == false && north == true && south == false && up == false && west == false) {
                State = 4815;
            } else if(east == false && north == false && south == true && up == true && west == true) {
                State = 4816;
            } else if(east == false && north == false && south == true && up == true && west == false) {
                State = 4817;
            } else if(east == false && north == false && south == true && up == false && west == true) {
                State = 4818;
            } else if(east == false && north == false && south == true && up == false && west == false) {
                State = 4819;
            } else if(east == false && north == false && south == false && up == true && west == true) {
                State = 4820;
            } else if(east == false && north == false && south == false && up == true && west == false) {
                State = 4821;
            } else if(east == false && north == false && south == false && up == false && west == true) {
                State = 4822;
            } else if(east == false && north == false && south == false && up == false && west == false) {
                State = 4823;
            }
        }
    }
}
