// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class WarpedPressurePlateBlock : BaseBlock {

        public bool Powered { get; }

        public WarpedPressurePlateBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 709, 15070) { }

        public WarpedPressurePlateBlock(Chunk chunk, int x, int y, int z, ushort state) : base(chunk, x, y, z 709, state) {
            if(state == 15069) {
                Powered = true;
            } else if(state == 15070) {
                Powered = false;
            }
        }

        public WarpedPressurePlateBlock(Chunk chunk, int x, int y, int z, bool powered) : base(chunk, x, y, z, 709, 15070) {
if(powered == true) {
                State = 15069;
            } else if(powered == false) {
                State = 15070;
            }
        }
    }
}
