// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class WarpedRoots : BaseBlock {

        public WarpedRoots(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 690, 14981) { }
    }
}
