// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class WeepingVinesPlant : BaseBlock {

        public WeepingVinesPlant(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 700, 15024) { }
    }
}
