// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class YellowConcretePowder : BaseBlock {

        public YellowConcretePowder(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 562, 9462) { }
    }
}
