// AUTOGENERATED. DO NOT MODIFY
using nylium.Core.Level;

namespace nylium.Core.Block.Blocks {

    public class YellowWoolBlock : BaseBlock {

        public YellowWoolBlock(Chunk chunk, int x, int y, int z) : base(chunk, x, y, z, 106, 1388) { }
    }
}
