name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Clean
      run: dotnet clean nylium.sln
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for Linux
      run: dotnet publish -r linux-x64 --self-contained false --no-restore
    - name: Build for Windows
      run: dotnet publish -r win-x64 --self-contained false --no-restore
    - name: Build for macOS
      run: dotnet publish -r osx-x64 --self-contained false --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: build
        path: nylium.Core/bin/Debug/netcoreapp3.1/*
